## 4. Merging the datas

Merging World Indicators Data (World Bank (GDP, GDP per capita, GDP growth, unemployment rate, inflation rate) & United Nations (HDI)) with Covid Vaccines and then with Covid Cases/Deaths

#### 4.1 Merging World Bank Data (GDP, GDP per capita, GDP growth, unemployment rate, inflation rate)
#### 4.2 Merging World Bank Data (GDP, GDP per capita, GDP growth, unemployment rate, inflation rate) & United Nations (HDI)
#### 4.3 Merging Economic Indicators (World Bank Data with United Nations (HDI)) with Covid Vaccines
#### 4.4 Merging the (Economic Indicators and Covid Vaccines) with Covid Cases/Deaths

#### 4.1 Merging World Bank Data (GDP, GDP per capita, GDP growth, unemployment rate, inflation rate)

##### 4.1.1 Merging GDP with GDP per capita

In [1]:
import pandas as pd

In [2]:
gdp2021 = pd.read_excel('gdp2021.xlsx')

In [3]:
gdp2021

,Country Name,Country Code,GDP 2021 (US$),Region,IncomeGroup
0,Aruba,ABW,3.126019e+09,Latin America & Caribbean,High income
1,Afghanistan,AFG,1.478686e+10,South Asia,Low income
2,Angola,AGO,6.740429e+10,Sub-Saharan Africa,Lower middle income
3,Albania,ALB,1.825579e+10,Europe & Central Asia,Upper middle income
4,Andorra,AND,3.330282e+09,Europe & Central Asia,High income
...,...,...,...,...,...
192,Samoa,WSM,8.438424e+08,East Asia & Pacific,Lower middle income
193,Kosovo,XKX,9.412034e+09,Europe & Central Asia,Upper middle income
194,South Africa,ZAF,4.190150e+11,Sub-Saharan Africa,Upper middle income
195,Zambia,ZMB,2.214763e+10,Sub-Saharan Africa,Low income
196,Zimbabwe,ZWE,2.837124e+10,Sub-Saharan Africa,Lower middle income

In [4]:
gdppercapita2021 = pd.read_excel('gdppercapita2021.xlsx')

In [5]:
gdppercapita2021

,Country Name,Country Code,GDP per capita 2021 (US$),Region,IncomeGroup
0,Aruba,ABW,29342.100858,Latin America & Caribbean,High income
1,Afghanistan,AFG,368.754614,South Asia,Low income
2,Angola,AGO,1953.533757,Sub-Saharan Africa,Lower middle income
3,Albania,ALB,6492.872012,Europe & Central Asia,Upper middle income
4,Andorra,AND,42137.327271,Europe & Central Asia,High income
...,...,...,...,...,...
192,Samoa,WSM,3857.318464,East Asia & Pacific,Lower middle income
193,Kosovo,XKX,5269.783901,Europe & Central Asia,Upper middle income
194,South Africa,ZAF,7055.044776,Sub-Saharan Africa,Upper middle income
195,Zambia,ZMB,1137.343633,Sub-Saharan Africa,Low income
196,Zimbabwe,ZWE,1773.920411,Sub-Saharan Africa,Lower middle income

In [6]:
gdppercapitagdp = gdp2021.merge(gdppercapita2021, on = ['Country Name','Country Code'], how='inner', indicator = True)

In [7]:
gdppercapitagdp

,Country Name,Country Code,GDP 2021 (US$),Region_x,IncomeGroup_x,GDP per capita 2021 (US$),Region_y,IncomeGroup_y,_merge
0,Aruba,ABW,3.126019e+09,Latin America & Caribbean,High income,29342.100858,Latin America & Caribbean,High income,both
1,Afghanistan,AFG,1.478686e+10,South Asia,Low income,368.754614,South Asia,Low income,both
2,Angola,AGO,6.740429e+10,Sub-Saharan Africa,Lower middle income,1953.533757,Sub-Saharan Africa,Lower middle income,both
3,Albania,ALB,1.825579e+10,Europe & Central Asia,Upper middle income,6492.872012,Europe & Central Asia,Upper middle income,both
4,Andorra,AND,3.330282e+09,Europe & Central Asia,High income,42137.327271,Europe & Central Asia,High income,both
...,...,...,...,...,...,...,...,...,...
192,Samoa,WSM,8.438424e+08,East Asia & Pacific,Lower middle income,3857.318464,East Asia & Pacific,Lower middle income,both
193,Kosovo,XKX,9.412034e+09,Europe & Central Asia,Upper middle income,5269.783901,Europe & Central Asia,Upper middle income,both
194,South Africa,ZAF,4.190150e+11,Sub-Saharan Africa,Upper middle income,7055.044776,Sub-Saharan Africa,Upper middle income,both
195,Zambia,ZMB,2.214763e+10,Sub-Saharan Africa,Low income,1137.343633,Sub-Saharan Africa,Low income,both
196,Zimbabwe,ZWE,2.837124e+10,Sub-Saharan Africa,Lower middle income,1773.920411,Sub-Saharan Africa,Lower middle income,both

In [8]:
gdppercapitagdp = gdppercapitagdp.iloc[:,[0,1,2,3,4,5]]

In [9]:
gdppercapitagdp

,Country Name,Country Code,GDP 2021 (US$),Region_x,IncomeGroup_x,GDP per capita 2021 (US$)
0,Aruba,ABW,3.126019e+09,Latin America & Caribbean,High income,29342.100858
1,Afghanistan,AFG,1.478686e+10,South Asia,Low income,368.754614
2,Angola,AGO,6.740429e+10,Sub-Saharan Africa,Lower middle income,1953.533757
3,Albania,ALB,1.825579e+10,Europe & Central Asia,Upper middle income,6492.872012
4,Andorra,AND,3.330282e+09,Europe & Central Asia,High income,42137.327271
...,...,...,...,...,...,...
192,Samoa,WSM,8.438424e+08,East Asia & Pacific,Lower middle income,3857.318464
193,Kosovo,XKX,9.412034e+09,Europe & Central Asia,Upper middle income,5269.783901
194,South Africa,ZAF,4.190150e+11,Sub-Saharan Africa,Upper middle income,7055.044776
195,Zambia,ZMB,2.214763e+10,Sub-Saharan Africa,Low income,1137.343633
196,Zimbabwe,ZWE,2.837124e+10,Sub-Saharan Africa,Lower middle income,1773.920411

In [10]:
gdppercapitagdp = gdppercapitagdp[gdppercapitagdp.columns[[0,1,2,5,3,4]]]

In [11]:
gdppercapitagdp

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),Region_x,IncomeGroup_x
0,Aruba,ABW,3.126019e+09,29342.100858,Latin America & Caribbean,High income
1,Afghanistan,AFG,1.478686e+10,368.754614,South Asia,Low income
2,Angola,AGO,6.740429e+10,1953.533757,Sub-Saharan Africa,Lower middle income
3,Albania,ALB,1.825579e+10,6492.872012,Europe & Central Asia,Upper middle income
4,Andorra,AND,3.330282e+09,42137.327271,Europe & Central Asia,High income
...,...,...,...,...,...,...
192,Samoa,WSM,8.438424e+08,3857.318464,East Asia & Pacific,Lower middle income
193,Kosovo,XKX,9.412034e+09,5269.783901,Europe & Central Asia,Upper middle income
194,South Africa,ZAF,4.190150e+11,7055.044776,Sub-Saharan Africa,Upper middle income
195,Zambia,ZMB,2.214763e+10,1137.343633,Sub-Saharan Africa,Low income
196,Zimbabwe,ZWE,2.837124e+10,1773.920411,Sub-Saharan Africa,Lower middle income

In [12]:
gdppercapitagdp.rename({'Region_x':'Region','IncomeGroup_x':'IncomeGroup'}, axis = 'columns', inplace = True)

In [13]:
gdppercapitagdp

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),Region,IncomeGroup
0,Aruba,ABW,3.126019e+09,29342.100858,Latin America & Caribbean,High income
1,Afghanistan,AFG,1.478686e+10,368.754614,South Asia,Low income
2,Angola,AGO,6.740429e+10,1953.533757,Sub-Saharan Africa,Lower middle income
3,Albania,ALB,1.825579e+10,6492.872012,Europe & Central Asia,Upper middle income
4,Andorra,AND,3.330282e+09,42137.327271,Europe & Central Asia,High income
...,...,...,...,...,...,...
192,Samoa,WSM,8.438424e+08,3857.318464,East Asia & Pacific,Lower middle income
193,Kosovo,XKX,9.412034e+09,5269.783901,Europe & Central Asia,Upper middle income
194,South Africa,ZAF,4.190150e+11,7055.044776,Sub-Saharan Africa,Upper middle income
195,Zambia,ZMB,2.214763e+10,1137.343633,Sub-Saharan Africa,Low income
196,Zimbabwe,ZWE,2.837124e+10,1773.920411,Sub-Saharan Africa,Lower middle income

#### 4.1.2 Merging GDP growth with gdppercapitagdp (the merge between GDP with GDP per capita)

In [14]:
gdpgrowth2021 = pd.read_excel('gdpgrowth2021.xlsx')

In [15]:
GDPs = gdpgrowth2021.merge(gdppercapitagdp, on = ['Country Code', 'Country Name'], how='inner', indicator = '_merge1')

In [16]:
GDPs

,Country Name,Country Code,GDP growth 2021 (annual %),Region_x,IncomeGroup_x,GDP 2021 (US$),GDP per capita 2021 (US$),Region_y,IncomeGroup_y,_merge1
0,Aruba,ABW,17.172509,Latin America & Caribbean,High income,3.126019e+09,29342.100858,Latin America & Caribbean,High income,both
1,Afghanistan,AFG,-20.737146,South Asia,Low income,1.478686e+10,368.754614,South Asia,Low income,both
2,Angola,AGO,1.100000,Sub-Saharan Africa,Lower middle income,6.740429e+10,1953.533757,Sub-Saharan Africa,Lower middle income,both
3,Albania,ALB,8.515501,Europe & Central Asia,Upper middle income,1.825579e+10,6492.872012,Europe & Central Asia,Upper middle income,both
4,Andorra,AND,8.949418,Europe & Central Asia,High income,3.330282e+09,42137.327271,Europe & Central Asia,High income,both
...,...,...,...,...,...,...,...,...,...,...
190,Samoa,WSM,-7.084588,East Asia & Pacific,Lower middle income,8.438424e+08,3857.318464,East Asia & Pacific,Lower middle income,both
191,Kosovo,XKX,10.745612,Europe & Central Asia,Upper middle income,9.412034e+09,5269.783901,Europe & Central Asia,Upper middle income,both
192,South Africa,ZAF,4.913097,Sub-Saharan Africa,Upper middle income,4.190150e+11,7055.044776,Sub-Saharan Africa,Upper middle income,both
193,Zambia,ZMB,4.598734,Sub-Saharan Africa,Low income,2.214763e+10,1137.343633,Sub-Saharan Africa,Low income,both
194,Zimbabwe,ZWE,8.468017,Sub-Saharan Africa,Lower middle income,2.837124e+10,1773.920411,Sub-Saharan Africa,Lower middle income,both

In [17]:
GDPs = GDPs.iloc[:, [0,1,2,3,4,5,6]]

In [18]:
GDPs.rename({'Region_x':'Region', 'IncomeGroup_x': 'IncomeGroup'}, axis = 1, inplace = True)

C:\Users\andre\anaconda3\lib\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [19]:
GDPs

,Country Name,Country Code,GDP growth 2021 (annual %),Region,IncomeGroup,GDP 2021 (US$),GDP per capita 2021 (US$)
0,Aruba,ABW,17.172509,Latin America & Caribbean,High income,3.126019e+09,29342.100858
1,Afghanistan,AFG,-20.737146,South Asia,Low income,1.478686e+10,368.754614
2,Angola,AGO,1.100000,Sub-Saharan Africa,Lower middle income,6.740429e+10,1953.533757
3,Albania,ALB,8.515501,Europe & Central Asia,Upper middle income,1.825579e+10,6492.872012
4,Andorra,AND,8.949418,Europe & Central Asia,High income,3.330282e+09,42137.327271
...,...,...,...,...,...,...,...
190,Samoa,WSM,-7.084588,East Asia & Pacific,Lower middle income,8.438424e+08,3857.318464
191,Kosovo,XKX,10.745612,Europe & Central Asia,Upper middle income,9.412034e+09,5269.783901
192,South Africa,ZAF,4.913097,Sub-Saharan Africa,Upper middle income,4.190150e+11,7055.044776
193,Zambia,ZMB,4.598734,Sub-Saharan Africa,Low income,2.214763e+10,1137.343633
194,Zimbabwe,ZWE,8.468017,Sub-Saharan Africa,Lower middle income,2.837124e+10,1773.920411

In [20]:
GDPs = GDPs[GDPs.columns[[0,1,5,6,2,3,4]]]

In [21]:
GDPs

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Region,IncomeGroup
0,Aruba,ABW,3.126019e+09,29342.100858,17.172509,Latin America & Caribbean,High income
1,Afghanistan,AFG,1.478686e+10,368.754614,-20.737146,South Asia,Low income
2,Angola,AGO,6.740429e+10,1953.533757,1.100000,Sub-Saharan Africa,Lower middle income
3,Albania,ALB,1.825579e+10,6492.872012,8.515501,Europe & Central Asia,Upper middle income
4,Andorra,AND,3.330282e+09,42137.327271,8.949418,Europe & Central Asia,High income
...,...,...,...,...,...,...,...
190,Samoa,WSM,8.438424e+08,3857.318464,-7.084588,East Asia & Pacific,Lower middle income
191,Kosovo,XKX,9.412034e+09,5269.783901,10.745612,Europe & Central Asia,Upper middle income
192,South Africa,ZAF,4.190150e+11,7055.044776,4.913097,Sub-Saharan Africa,Upper middle income
193,Zambia,ZMB,2.214763e+10,1137.343633,4.598734,Sub-Saharan Africa,Low income
194,Zimbabwe,ZWE,2.837124e+10,1773.920411,8.468017,Sub-Saharan Africa,Lower middle income

#### 4.1.3 Merging between Unemployment rate and Inflation Rate

In [22]:
inflationrate2021 = pd.read_excel('inflationrate2021.xlsx')

In [23]:
inflationrate2021

,Country Name,Country Code,Inflation Rate 2021 (%),Region,IncomeGroup
0,Angola,AGO,25.754266,Sub-Saharan Africa,Lower middle income
1,Albania,ALB,2.041472,Europe & Central Asia,Upper middle income
2,Armenia,ARM,7.184836,Europe & Central Asia,Upper middle income
3,Antigua and Barbuda,ATG,2.062996,Latin America & Caribbean,High income
4,Australia,AUS,2.863910,East Asia & Pacific,High income
...,...,...,...,...,...
152,Samoa,WSM,3.133205,East Asia & Pacific,Lower middle income
153,Kosovo,XKX,3.353691,Europe & Central Asia,Upper middle income
154,South Africa,ZAF,4.611672,Sub-Saharan Africa,Upper middle income
155,Zambia,ZMB,22.021234,Sub-Saharan Africa,Low income
156,Zimbabwe,ZWE,98.546105,Sub-Saharan Africa,Lower middle income

In [24]:
unemploymentrate2021 = pd.read_excel('unemploymentrate2021.xlsx')

In [25]:
unemploymentrate2021

,Country Name,Country Code,Unemployment Rate 2021 (%),Region,IncomeGroup
0,Angola,AGO,10.384,Sub-Saharan Africa,Lower middle income
1,Albania,ALB,12.683,Europe & Central Asia,Upper middle income
2,United Arab Emirates,ARE,3.110,Middle East & North Africa,High income
3,Argentina,ARG,8.740,Latin America & Caribbean,Upper middle income
4,Armenia,ARM,12.729,Europe & Central Asia,Upper middle income
...,...,...,...,...,...
179,Samoa,WSM,9.910,East Asia & Pacific,Lower middle income
180,"Yemen, Rep.",YEM,13.887,Middle East & North Africa,Low income
181,South Africa,ZAF,28.770,Sub-Saharan Africa,Upper middle income
182,Zambia,ZMB,6.220,Sub-Saharan Africa,Low income
183,Zimbabwe,ZWE,8.067,Sub-Saharan Africa,Lower middle income

In [26]:
unemploymentinflationrate = inflationrate2021.merge(unemploymentrate2021, on = ['Country Code', 'Country Name'], how='inner', indicator = '_merge2')

In [27]:
unemploymentinflationrate.head()

,Country Name,Country Code,Inflation Rate 2021 (%),Region_x,IncomeGroup_x,Unemployment Rate 2021 (%),Region_y,IncomeGroup_y,_merge2
0,Angola,AGO,25.754266,Sub-Saharan Africa,Lower middle income,10.384,Sub-Saharan Africa,Lower middle income,both
1,Albania,ALB,2.041472,Europe & Central Asia,Upper middle income,12.683,Europe & Central Asia,Upper middle income,both
2,Armenia,ARM,7.184836,Europe & Central Asia,Upper middle income,12.729,Europe & Central Asia,Upper middle income,both
3,Australia,AUS,2.863910,East Asia & Pacific,High income,5.120,East Asia & Pacific,High income,both
4,Austria,AUT,2.766667,Europe & Central Asia,High income,6.180,Europe & Central Asia,High income,both

In [28]:
unemploymentinflationrate = unemploymentinflationrate.iloc[:, [0,1,2,3,4,5]]

In [29]:
unemploymentinflationrate.rename({'Region_x':'Region','IncomeGroup_x':'IncomeGroup'}, axis = 'columns', inplace = True)

In [30]:
unemploymentinflationrate = unemploymentinflationrate[unemploymentinflationrate.columns[[0,1,2,5,3,4]]]

In [31]:
unemploymentinflationrate

,Country Name,Country Code,Inflation Rate 2021 (%),Unemployment Rate 2021 (%),Region,IncomeGroup
0,Angola,AGO,25.754266,10.384,Sub-Saharan Africa,Lower middle income
1,Albania,ALB,2.041472,12.683,Europe & Central Asia,Upper middle income
2,Armenia,ARM,7.184836,12.729,Europe & Central Asia,Upper middle income
3,Australia,AUS,2.863910,5.120,East Asia & Pacific,High income
4,Austria,AUT,2.766667,6.180,Europe & Central Asia,High income
...,...,...,...,...,...,...
147,Vanuatu,VUT,2.343284,2.118,East Asia & Pacific,Lower middle income
148,Samoa,WSM,3.133205,9.910,East Asia & Pacific,Lower middle income
149,South Africa,ZAF,4.611672,28.770,Sub-Saharan Africa,Upper middle income
150,Zambia,ZMB,22.021234,6.220,Sub-Saharan Africa,Low income
151,Zimbabwe,ZWE,98.546105,8.067,Sub-Saharan Africa,Lower middle income

#### 4.1.4 Merging between GDPs (gdp, gdp per capita and gdp growth) with unemploymentinflationrate (unemployment rate and inflation rate)

In [32]:
worldbankeconomicindicators = GDPs.merge(unemploymentinflationrate, on = ['Country Code', 'Country Name'], how='inner', indicator = '_merge3')

In [33]:
worldbankeconomicindicators.head(3)

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Region_x,IncomeGroup_x,Inflation Rate 2021 (%),Unemployment Rate 2021 (%),Region_y,IncomeGroup_y,_merge3
0,Angola,AGO,6.740429e+10,1953.533757,1.100000,Sub-Saharan Africa,Lower middle income,25.754266,10.384,Sub-Saharan Africa,Lower middle income,both
1,Albania,ALB,1.825579e+10,6492.872012,8.515501,Europe & Central Asia,Upper middle income,2.041472,12.683,Europe & Central Asia,Upper middle income,both
2,Armenia,ARM,1.386141e+10,4966.513471,5.700000,Europe & Central Asia,Upper middle income,7.184836,12.729,Europe & Central Asia,Upper middle income,both

In [34]:
worldbankeconomicindicators.drop(['Region_y','IncomeGroup_y','_merge3'], axis = 1, inplace = True)

In [35]:
worldbankeconomicindicators.head()

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Region_x,IncomeGroup_x,Inflation Rate 2021 (%),Unemployment Rate 2021 (%)
0,Angola,AGO,6.740429e+10,1953.533757,1.100000,Sub-Saharan Africa,Lower middle income,25.754266,10.384
1,Albania,ALB,1.825579e+10,6492.872012,8.515501,Europe & Central Asia,Upper middle income,2.041472,12.683
2,Armenia,ARM,1.386141e+10,4966.513471,5.700000,Europe & Central Asia,Upper middle income,7.184836,12.729
3,Australia,AUS,1.552667e+12,60443.109165,2.236212,East Asia & Pacific,High income,2.863910,5.120
4,Austria,AUT,4.803684e+11,53637.705711,4.556851,Europe & Central Asia,High income,2.766667,6.180

In [36]:
worldbankeconomicindicators.rename({'Region_x':'Region', 'IncomeGroup_x':'IncomeGroup'}, axis = 'columns', inplace = True)

In [37]:
worldbankeconomicindicators.head(3)

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Region,IncomeGroup,Inflation Rate 2021 (%),Unemployment Rate 2021 (%)
0,Angola,AGO,6.740429e+10,1953.533757,1.100000,Sub-Saharan Africa,Lower middle income,25.754266,10.384
1,Albania,ALB,1.825579e+10,6492.872012,8.515501,Europe & Central Asia,Upper middle income,2.041472,12.683
2,Armenia,ARM,1.386141e+10,4966.513471,5.700000,Europe & Central Asia,Upper middle income,7.184836,12.729

In [38]:
worldbankeconomicindicators = worldbankeconomicindicators[worldbankeconomicindicators.columns[[0,1,2,3,4,7,8,5,6]]]

In [39]:
worldbankeconomicindicators

,Country Name,Country Code,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Inflation Rate 2021 (%),Unemployment Rate 2021 (%),Region,IncomeGroup
0,Angola,AGO,6.740429e+10,1953.533757,1.100000,25.754266,10.384,Sub-Saharan Africa,Lower middle income
1,Albania,ALB,1.825579e+10,6492.872012,8.515501,2.041472,12.683,Europe & Central Asia,Upper middle income
2,Armenia,ARM,1.386141e+10,4966.513471,5.700000,7.184836,12.729,Europe & Central Asia,Upper middle income
3,Australia,AUS,1.552667e+12,60443.109165,2.236212,2.863910,5.120,East Asia & Pacific,High income
4,Austria,AUT,4.803684e+11,53637.705711,4.556851,2.766667,6.180,Europe & Central Asia,High income
...,...,...,...,...,...,...,...,...,...
145,Vanuatu,VUT,9.563327e+08,2996.621062,0.449256,2.343284,2.118,East Asia & Pacific,Lower middle income
146,Samoa,WSM,8.438424e+08,3857.318464,-7.084588,3.133205,9.910,East Asia & Pacific,Lower middle income
147,South Africa,ZAF,4.190150e+11,7055.044776,4.913097,4.611672,28.770,Sub-Saharan Africa,Upper middle income
148,Zambia,ZMB,2.214763e+10,1137.343633,4.598734,22.021234,6.220,Sub-Saharan Africa,Low income
149,Zimbabwe,ZWE,2.837124e+10,1773.920411,8.468017,98.546105,8.067,Sub-Saharan Africa,Lower middle income

### 4.2 Merging World Bank Data (GDP, GDP per capita, GDP growth, unemployment rate, inflation rate) & United Nations (HDI)

In [40]:
hdiranking2021 = pd.read_excel('hdiranking2021.xlsx')

In [41]:
hdiranking2021

,Country Code,HDI rank,Country,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
0,CHE,1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540
1,NOR,2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220
2,ISL,3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810
3,HKG,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400
4,AUS,5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350
...,...,...,...,...,...,...,...,...
184,MOZ,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924
185,MLI,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443
186,BDI,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
187,CAF,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611
188,NER,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936

In [42]:
economicindicators = hdiranking2021.merge(worldbankeconomicindicators, on = ['Country Code'], how='inner', indicator = '_merge4')

In [43]:
economicindicators

,Country Code,HDI rank,Country,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,Country Name,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Inflation Rate 2021 (%),Unemployment Rate 2021 (%),Region,IncomeGroup,_merge4
0,CHE,1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,Switzerland,8.006402e+11,91991.600458,4.221717,0.581814,5.100,Europe & Central Asia,High income,both
1,NOR,2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,Norway,4.821749e+11,89154.276093,3.880936,3.483881,4.370,Europe & Central Asia,High income,both
2,ISL,3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,Iceland,2.560242e+10,68727.636665,4.403045,4.444240,6.020,Europe & Central Asia,High income,both
3,HKG,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,"Hong Kong SAR, China",3.691764e+11,49800.542414,6.343106,1.568758,5.170,East Asia & Pacific,High income,both
4,AUS,5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,Australia,1.552667e+12,60443.109165,2.236212,2.863910,5.120,East Asia & Pacific,High income,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,MOZ,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924,Mozambique,1.577676e+10,491.839113,2.363988,5.688487,3.939,Sub-Saharan Africa,Low income,both
145,MLI,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443,Mali,1.914046e+10,873.794862,3.052614,3.925603,2.603,Sub-Saharan Africa,Low income,both
146,BDI,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,Burundi,2.779813e+09,221.477676,1.795300,8.404538,1.132,Sub-Saharan Africa,Low income,both
147,CAF,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,Central African Republic,2.516498e+09,461.137490,0.900000,4.259364,6.458,Sub-Saharan Africa,Low income,both
148,NER,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,Niger,1.491500e+10,590.629455,1.387129,3.837868,0.668,Sub-Saharan Africa,Low income,both

In [44]:
economicindicators.drop({'Country Name', '_merge4'}, axis = 'columns', inplace = True)

In [45]:
economicindicators.head(3)

,Country Code,HDI rank,Country,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Inflation Rate 2021 (%),Unemployment Rate 2021 (%),Region,IncomeGroup
0,CHE,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,8.006402e+11,91991.600458,4.221717,0.581814,5.10,Europe & Central Asia,High income
1,NOR,2,Norway,0.961,83.2339,18.185200,13.00363,64660.10622,4.821749e+11,89154.276093,3.880936,3.483881,4.37,Europe & Central Asia,High income
2,ISL,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,2.560242e+10,68727.636665,4.403045,4.444240,6.02,Europe & Central Asia,High income

In [46]:
economicindicators = economicindicators[economicindicators.columns[[0,2,1,3,4,5,6,7,8,9,10,11,12,13,14]]]

In [47]:
economicindicators

,Country Code,Country,HDI rank,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GDP 2021 (US$),GDP per capita 2021 (US$),GDP growth 2021 (annual %),Inflation Rate 2021 (%),Unemployment Rate 2021 (%),Region,IncomeGroup
0,CHE,Switzerland,1,0.962,83.9872,16.500299,13.859660,66933.004540,8.006402e+11,91991.600458,4.221717,0.581814,5.100,Europe & Central Asia,High income
1,NOR,Norway,2,0.961,83.2339,18.185200,13.003630,64660.106220,4.821749e+11,89154.276093,3.880936,3.483881,4.370,Europe & Central Asia,High income
2,ISL,Iceland,3,0.959,82.6782,19.163059,13.767170,55782.049810,2.560242e+10,68727.636665,4.403045,4.444240,6.020,Europe & Central Asia,High income
3,HKG,"Hong Kong, China (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,3.691764e+11,49800.542414,6.343106,1.568758,5.170,East Asia & Pacific,High income
4,AUS,Australia,5,0.951,84.5265,21.054590,12.726820,49238.433350,1.552667e+12,60443.109165,2.236212,2.863910,5.120,East Asia & Pacific,High income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,MOZ,Mozambique,185,0.446,59.3247,10.219152,3.197642,1198.073924,1.577676e+10,491.839113,2.363988,5.688487,3.939,Sub-Saharan Africa,Low income
145,MLI,Mali,186,0.428,58.9414,7.423038,2.310000,2132.629443,1.914046e+10,873.794862,3.052614,3.925603,2.603,Sub-Saharan Africa,Low income
146,BDI,Burundi,187,0.426,61.6627,10.722722,3.129267,731.786709,2.779813e+09,221.477676,1.795300,8.404538,1.132,Sub-Saharan Africa,Low income
147,CAF,Central African Republic,188,0.404,53.8947,8.040172,4.334000,966.058611,2.516498e+09,461.137490,0.900000,4.259364,6.458,Sub-Saharan Africa,Low income
148,NER,Niger,189,0.400,61.5763,6.957112,2.116717,1239.866936,1.491500e+10,590.629455,1.387129,3.837868,0.668,Sub-Saharan Africa,Low income

In [48]:
economicindicators.to_excel('economicindicators2021.xlsx', index = False)

### 4.3 Merging Economic Indicator (World Bank Data with United Nations (HDI)) with Covid Vaccines

####  merging economicindicators with covid19vaccinations first because it has isocode, then do the final merge with covid cases/deaths

In [49]:
covidvaccinations = pd.read_excel('covidvaccinationsApril5th2023.xlsx')

In [50]:
covidvaccinations

,location,total_vaccinations,iso_code,date,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,Afghanistan,16586584,AFG,2023-04-02,14526772,13815117,36587.0,218908,40.33,35.32,33.59,5323
1,Africa,795123796,OWID_AFR,2023-04-02,517915154,429535865,4248978.0,4180515,55.73,36.30,30.11,2930
2,Albania,3070468,ALB,2023-03-19,1347054,1276432,23655.0,17565,108.03,47.39,44.91,6180
3,Algeria,15267442,DZA,2022-09-04,7840131,6481186,147230.0,256927,34.00,17.46,14.43,5722
4,Andorra,156957,AND,2023-02-26,57904,53492,2829.0,1762,196.58,72.52,67.00,22068
...,...,...,...,...,...,...,...,...,...,...,...,...
230,Wallis and Futuna,18058,WLF,2023-01-23,7150,6803,NaN,432,155.73,61.66,58.67,37254
231,World,13371543980,OWID_WRL,2023-04-04,5571240761,5140195435,49672851.0,43692625,167.67,69.86,64.45,5479
232,Yemen,1258021,YEM,2023-03-19,1018387,773549,NaN,10240,3.73,3.02,2.30,304
233,Zambia,12792112,ZMB,2023-03-15,11158619,8747040,224617.0,180289,63.90,55.74,43.70,9006
234,Zimbabwe,12222754,ZWE,2022-10-09,6437808,4751270,182395.0,121347,74.89,39.45,29.11,7435

In [51]:
economicindicatorsvaccines = economicindicators.merge(covidvaccinations, left_on = ['Country Code'], right_on = ['iso_code'], how='inner', indicator = True)

In [52]:
economicindicatorsvaccines

,Country Code,Country,HDI rank,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GDP 2021 (US$),GDP per capita 2021 (US$),...,date,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,_merge
0,CHE,Switzerland,1,0.962,83.9872,16.500299,13.859660,66933.004540,8.006402e+11,91991.600458,...,2023-04-03,6096607,6013015,113605.0,92595,193.77,69.75,68.80,10594,both
1,NOR,Norway,2,0.961,83.2339,18.185200,13.003630,64660.106220,4.821749e+11,89154.276093,...,2022-11-13,4346995,4054726,138686.0,69148,223.50,79.99,74.61,12724,both
2,ISL,Iceland,3,0.959,82.6782,19.163059,13.767170,55782.049810,2.560242e+10,68727.636665,...,2022-03-29,309770,290193,21266.0,7546,216.00,83.07,77.82,20236,both
3,HKG,"Hong Kong, China (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,3.691764e+11,49800.542414,...,2023-04-02,6914894,6798392,102019.0,86321,276.99,92.34,90.78,11527,both
4,AUS,Australia,5,0.951,84.5265,21.054590,12.726820,49238.433350,1.552667e+12,60443.109165,...,2023-02-02,22236698,21654488,351226.0,295848,243.27,84.95,82.72,11302,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,MOZ,Mozambique,185,0.446,59.3247,10.219152,3.197642,1198.073924,1.577676e+10,491.839113,...,2023-01-29,18641485,18466955,295812.0,588728,89.35,56.54,56.01,17857,both
145,MLI,Mali,186,0.428,58.9414,7.423038,2.310000,2132.629443,1.914046e+10,873.794862,...,2023-03-19,3959022,3247719,NaN,58966,23.77,17.52,14.37,2610,both
146,BDI,Burundi,187,0.426,61.6627,10.722722,3.129267,731.786709,2.779813e+09,221.477676,...,2023-03-19,33814,33225,109.0,410,0.28,0.26,0.26,32,both
147,CAF,Central African Republic,188,0.404,53.8947,8.040172,4.334000,966.058611,2.516498e+09,461.137490,...,2023-03-26,2381935,2266531,12887.0,25469,48.20,42.69,40.63,4565,both
148,NER,Niger,189,0.400,61.5763,6.957112,2.116717,1239.866936,1.491500e+10,590.629455,...,2023-03-12,6217508,5454196,NaN,178386,28.00,23.72,20.81,6807,both

In [53]:
economicindicatorsvaccines.drop({'location', 'iso_code','_merge'}, axis = 'columns', inplace = True)

In [54]:
economicindicatorsvaccines.head(3)

,Country Code,Country,HDI rank,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GDP 2021 (US$),GDP per capita 2021 (US$),...,total_vaccinations,date,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,CHE,Switzerland,1,0.962,83.9872,16.500299,13.85966,66933.00454,8.006402e+11,91991.600458,...,16936227,2023-04-03,6096607,6013015,113605.0,92595,193.77,69.75,68.80,10594
1,NOR,Norway,2,0.961,83.2339,18.185200,13.00363,64660.10622,4.821749e+11,89154.276093,...,12145560,2022-11-13,4346995,4054726,138686.0,69148,223.50,79.99,74.61,12724
2,ISL,Iceland,3,0.959,82.6782,19.163059,13.76717,55782.04981,2.560242e+10,68727.636665,...,805469,2022-03-29,309770,290193,21266.0,7546,216.00,83.07,77.82,20236

#### finding the iso code 3 first for covid cases/deaths before the merge

In [55]:
covidcasesdeaths = pd.read_excel('covidcasesdeaths_April5th2023.xlsx')

In [56]:
covidcasesdeaths

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.0,0.9,"2,046"
3,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Vatican City,29,NaN,NaN,NaN,29,NaN,0,NaN,NaN,799,Europe,NaN,NaN,NaN
227,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,NaN,"626,161",Africa,NaN,NaN,NaN
228,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,Tokelau,5,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,"1,378",Australia/Oceania,NaN,NaN,"3,628"
230,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,"160,000,000","1,448,471,400",Asia,NaN,NaN,82

#### if the merge were to be done by country name, a lot of information would be lost; that's why finding the iso code 3 is so important to do the merge

In [57]:
print(covidcasesdeaths['Country,Other'].tolist())

['USA', 'India', 'France', 'Germany', 'Brazil', 'Japan', 'S. Korea', 'Italy', 'UK', 'Russia', 'Turkey', 'Spain', 'Vietnam', 'Australia', 'Taiwan', 'Argentina', 'Netherlands', 'Iran', 'Mexico', 'Indonesia', 'Poland', 'Colombia', 'Austria', 'Greece', 'Portugal', 'Ukraine', 'Chile', 'Malaysia', 'Israel', 'Belgium', 'DPRK', 'Thailand', 'Czechia', 'Canada', 'Peru', 'Switzerland', 'Philippines', 'South Africa', 'Romania', 'Denmark', 'Hong Kong', 'Sweden', 'Serbia', 'Iraq', 'New Zealand', 'Singapore', 'Hungary', 'Bangladesh', 'Slovakia', 'Georgia', 'Jordan', 'Ireland', 'Pakistan', 'Norway', 'Finland', 'Kazakhstan', 'Slovenia', 'Lithuania', 'Bulgaria', 'Morocco', 'Croatia', 'Guatemala', 'Lebanon', 'Costa Rica', 'Bolivia', 'Tunisia', 'Cuba', 'Ecuador', 'UAE', 'Uruguay', 'Panama', 'Mongolia', 'Nepal', 'Belarus', 'Latvia', 'Saudi Arabia', 'Azerbaijan', 'Paraguay', 'Bahrain', 'Sri Lanka', 'Kuwait', 'Dominican Republic', 'Cyprus', 'Myanmar', 'Palestine', 'Moldova', 'Estonia', 'Venezuela', 'Egypt', 'Libya', 'Qatar', 'Ethiopia', 'RÃ©union', 'Honduras', 'Armenia', 'Bosnia and Herzegovina', 'Oman', 'North Macedonia', 'Zambia', 'Kenya', 'Albania', 'Botswana', 'Luxembourg', 'Montenegro', 'Brunei', 'Algeria', 'Nigeria', 'Zimbabwe', 'Uzbekistan', 'Mozambique', 'Martinique', 'Laos', 'Afghanistan', 'Iceland', 'Kyrgyzstan', 'Guadeloupe', 'El Salvador', 'Trinidad and Tobago', 'Maldives', 'Ghana', 'Namibia', 'Uganda', 'Jamaica', 'Cambodia', 'Rwanda', 'Cameroon', 'Malta', 'Barbados', 'Angola', 'Channel Islands', 'French Guiana', 'DRC', 'Senegal', 'Malawi', 'Ivory Coast', 'Suriname', 'New Caledonia', 'French Polynesia', 'Eswatini', 'Guyana', 'Belize', 'Fiji', 'Madagascar', 'Sudan', 'Mauritania', 'Cabo Verde', 'Bhutan', 'Syria', 'Burundi', 'Seychelles', 'Gabon', 'Andorra', 'Papua New Guinea', 'CuraÃ§ao', 'Aruba', 'Tanzania', 'Mayotte', 'Mauritius', 'Togo', 'Guinea', 'Isle of Man', 'Bahamas', 'Lesotho', 'Faeroe Islands', 'Haiti', 'Mali', 'Cayman Islands', 'Saint Lucia', 'Benin', 'Somalia', 'Micronesia', 'Congo', 'Solomon Islands', 'San Marino', 'Timor-Leste', 'Burkina Faso', 'Liechtenstein', 'Gibraltar', 'Grenada', 'Bermuda', 'Nicaragua', 'South Sudan', 'Tajikistan', 'Equatorial Guinea', 'Tonga', 'Samoa', 'Monaco', 'Marshall Islands', 'Dominica', 'Djibouti', 'CAR', 'Gambia', 'Saint Martin', 'Vanuatu', 'Greenland', 'Yemen', 'Caribbean Netherlands', 'Sint Maarten', 'Eritrea', 'Niger', 'St. Vincent Grenadines', 'Guinea-Bissau', 'Antigua and Barbuda', 'Comoros', 'Liberia', 'Sierra Leone', 'Chad', 'British Virgin Islands', 'Cook Islands', 'Saint Kitts and Nevis', 'Turks and Caicos', 'Sao Tome and Principe', 'Palau', 'St. Barth', 'Nauru', 'Kiribati', 'Anguilla', 'Macao', 'Saint Pierre Miquelon', 'Wallis and Futuna', 'Tuvalu', 'Saint Helena', 'Falkland Islands', 'Montserrat', 'Niue', 'Diamond Princess', 'Vatican City', 'Western Sahara', 'MS Zaandam', 'Tokelau', 'China']

In [58]:
import country_converter as coco
some_names = ['USA', 'India', 'France', 'Germany', 'Brazil', 'Japan', 'S. Korea', 'Italy', 'UK', 'Russia', 'Turkey', 'Spain', 'Vietnam', 'Australia', 'Taiwan', 'Argentina', 'Netherlands', 'Iran', 'Mexico', 'Indonesia', 'Poland', 'Colombia', 'Austria', 'Greece', 'Portugal', 'Ukraine', 'Chile', 'Malaysia', 'Israel', 'Belgium', 'DPRK', 'Thailand', 'Czechia', 'Canada', 'Peru', 'Switzerland', 'Philippines', 'South Africa', 'Romania', 'Denmark', 'Hong Kong', 'Sweden', 'Serbia', 'Iraq', 'New Zealand', 'Singapore', 'Hungary', 'Bangladesh', 'Slovakia', 'Georgia', 'Jordan', 'Ireland', 'Pakistan', 'Norway', 'Finland', 'Kazakhstan', 'Slovenia', 'Lithuania', 'Bulgaria', 'Morocco', 'Croatia', 'Guatemala', 'Lebanon', 'Costa Rica', 'Bolivia', 'Tunisia', 'Cuba', 'Ecuador', 'UAE', 'Uruguay', 'Panama', 'Mongolia', 'Nepal', 'Belarus', 'Latvia', 'Saudi Arabia', 'Azerbaijan', 'Paraguay', 'Bahrain', 'Sri Lanka', 'Kuwait', 'Dominican Republic', 'Cyprus', 'Myanmar', 'Palestine', 'Moldova', 'Estonia', 'Venezuela', 'Egypt', 'Libya', 'Qatar', 'Ethiopia', 'RÃ©union', 'Honduras', 'Armenia', 'Bosnia and Herzegovina', 'Oman', 'North Macedonia', 'Zambia', 'Kenya', 'Albania', 'Botswana', 'Luxembourg', 'Montenegro', 'Brunei', 'Algeria', 'Nigeria', 'Zimbabwe', 'Uzbekistan', 'Mozambique', 'Martinique', 'Laos', 'Afghanistan', 'Iceland', 'Kyrgyzstan', 'Guadeloupe', 'El Salvador', 'Trinidad and Tobago', 'Maldives', 'Ghana', 'Namibia', 'Uganda', 'Jamaica', 'Cambodia', 'Rwanda', 'Cameroon', 'Malta', 'Barbados', 'Angola', 'Channel Islands', 'French Guiana', 'DRC', 'Senegal', 'Malawi', 'Ivory Coast', 'Suriname', 'New Caledonia', 'French Polynesia', 'Eswatini', 'Guyana', 'Belize', 'Fiji', 'Madagascar', 'Sudan', 'Mauritania', 'Cabo Verde', 'Bhutan', 'Syria', 'Burundi', 'Seychelles', 'Gabon', 'Andorra', 'Papua New Guinea', 'CuraÃ§ao', 'Aruba', 'Tanzania', 'Mayotte', 'Mauritius', 'Togo', 'Guinea', 'Isle of Man', 'Bahamas', 'Lesotho', 'Faeroe Islands', 'Haiti', 'Mali', 'Cayman Islands', 'Saint Lucia', 'Benin', 'Somalia', 'Micronesia', 'Congo', 'Solomon Islands', 'San Marino', 'Timor-Leste', 'Burkina Faso', 'Liechtenstein', 'Gibraltar', 'Grenada', 'Bermuda', 'Nicaragua', 'South Sudan', 'Tajikistan', 'Equatorial Guinea', 'Tonga', 'Samoa', 'Monaco', 'Marshall Islands', 'Dominica', 'Djibouti', 'CAR', 'Gambia', 'Saint Martin', 'Vanuatu', 'Greenland', 'Yemen', 'Caribbean Netherlands', 'Sint Maarten', 'Eritrea', 'Niger', 'St. Vincent Grenadines', 'Guinea-Bissau', 'Antigua and Barbuda', 'Comoros', 'Liberia', 'Sierra Leone', 'Chad', 'British Virgin Islands', 'Cook Islands', 'Saint Kitts and Nevis', 'Turks and Caicos', 'Sao Tome and Principe', 'Palau', 'St. Barth', 'Nauru', 'Kiribati', 'Anguilla', 'Macao', 'Saint Pierre Miquelon', 'Wallis and Futuna', 'Tuvalu', 'Saint Helena', 'Falkland Islands', 'Montserrat', 'Niue', 'Diamond Princess', 'Vatican City', 'Western Sahara', 'MS Zaandam', 'Tokelau', 'China']
standard_names = coco.convert(names=some_names, to='ISO3')
print(standard_names)

UAE not found in ISO3
Channel Islands not found in regex
DRC not found in ISO3
CAR not found in ISO3
Diamond Princess not found in regex
MS Zaandam not found in regex

['USA', 'IND', 'FRA', 'DEU', 'BRA', 'JPN', 'KOR', 'ITA', 'GBR', 'RUS', 'TUR', 'ESP', 'VNM', 'AUS', 'TWN', 'ARG', 'NLD', 'IRN', 'MEX', 'IDN', 'POL', 'COL', 'AUT', 'GRC', 'PRT', 'UKR', 'CHL', 'MYS', 'ISR', 'BEL', 'PRK', 'THA', 'CZE', 'CAN', 'PER', 'CHE', 'PHL', 'ZAF', 'ROU', 'DNK', 'HKG', 'SWE', 'SRB', 'IRQ', 'NZL', 'SGP', 'HUN', 'BGD', 'SVK', 'GEO', 'JOR', 'IRL', 'PAK', 'NOR', 'FIN', 'KAZ', 'SVN', 'LTU', 'BGR', 'MAR', 'HRV', 'GTM', 'LBN', 'CRI', 'BOL', 'TUN', 'CUB', 'ECU', 'not found', 'URY', 'PAN', 'MNG', 'NPL', 'BLR', 'LVA', 'SAU', 'AZE', 'PRY', 'BHR', 'LKA', 'KWT', 'DOM', 'CYP', 'MMR', 'PSE', 'MDA', 'EST', 'VEN', 'EGY', 'LBY', 'QAT', 'ETH', 'REU', 'HND', 'ARM', 'BIH', 'OMN', 'MKD', 'ZMB', 'KEN', 'ALB', 'BWA', 'LUX', 'MNE', 'BRN', 'DZA', 'NGA', 'ZWE', 'UZB', 'MOZ', 'MTQ', 'LAO', 'AFG', 'ISL', 'KGZ', 'GLP', 'SLV', 'TTO', 'MDV', 'GHA', 'NAM', 'UGA', 'JAM', 'KHM', 'RWA', 'CMR', 'MLT', 'BRB', 'AGO', 'not found', 'GUF', 'not found', 'SEN', 'MWI', 'CIV', 'SUR', 'NCL', 'PYF', 'SWZ', 'GUY', 'BLZ', 'FJI', 'MDG', 'SDN', 'MRT', 'CPV', 'BTN', 'SYR', 'BDI', 'SYC', 'GAB', 'AND', 'PNG', 'CUW', 'ABW', 'TZA', 'MYT', 'MUS', 'TGO', 'GIN', 'IMN', 'BHS', 'LSO', 'FRO', 'HTI', 'MLI', 'CYM', 'LCA', 'BEN', 'SOM', 'FSM', 'COG', 'SLB', 'SMR', 'TLS', 'BFA', 'LIE', 'GIB', 'GRD', 'BMU', 'NIC', 'SSD', 'TJK', 'GNQ', 'TON', 'WSM', 'MCO', 'MHL', 'DMA', 'DJI', 'not found', 'GMB', 'MAF', 'VUT', 'GRL', 'YEM', 'BES', 'SXM', 'ERI', 'NER', 'VCT', 'GNB', 'ATG', 'COM', 'LBR', 'SLE', 'TCD', 'VGB', 'COK', 'KNA', 'TCA', 'STP', 'PLW', 'BLM', 'NRU', 'KIR', 'AIA', 'MAC', 'SPM', 'WLF', 'TUV', 'SHN', 'FLK', 'MSR', 'NIU', 'not found', 'VAT', 'ESH', 'not found', 'TKL', 'CHN']

In [59]:
covidcasesdeaths['Country,Other'].str.replace('UK','United Kingdom')

0                 USA
1               India
2              France
3             Germany
4              Brazil
            ...
226      Vatican City
227    Western Sahara
228        MS Zaandam
229           Tokelau
230             China
Name: Country,Other, Length: 231, dtype: object

In [60]:
covidcasesdeaths['Country,Other'] = covidcasesdeaths['Country,Other'].str.replace('UK','United Kingdom')
covidcasesdeaths['Country,Other'] = covidcasesdeaths['Country,Other'].str.replace('UAE','ARE')
covidcasesdeaths['Country,Other'] = covidcasesdeaths['Country,Other'].str.replace('DRC','COD')
covidcasesdeaths['Country,Other'] = covidcasesdeaths['Country,Other'].str.replace('CAR','CAF')

In [61]:
covidcasesdeaths['Country,Other']

0                 USA
1               India
2              France
3             Germany
4              Brazil
            ...
226      Vatican City
227    Western Sahara
228        MS Zaandam
229           Tokelau
230             China
Name: Country,Other, Length: 231, dtype: object

In [62]:
print(covidcasesdeaths['Country,Other'].tolist())

['USA', 'India', 'France', 'Germany', 'Brazil', 'Japan', 'S. Korea', 'Italy', 'United Kingdom', 'Russia', 'Turkey', 'Spain', 'Vietnam', 'Australia', 'Taiwan', 'Argentina', 'Netherlands', 'Iran', 'Mexico', 'Indonesia', 'Poland', 'Colombia', 'Austria', 'Greece', 'Portugal', 'Ukraine', 'Chile', 'Malaysia', 'Israel', 'Belgium', 'DPRK', 'Thailand', 'Czechia', 'Canada', 'Peru', 'Switzerland', 'Philippines', 'South Africa', 'Romania', 'Denmark', 'Hong Kong', 'Sweden', 'Serbia', 'Iraq', 'New Zealand', 'Singapore', 'Hungary', 'Bangladesh', 'Slovakia', 'Georgia', 'Jordan', 'Ireland', 'Pakistan', 'Norway', 'Finland', 'Kazakhstan', 'Slovenia', 'Lithuania', 'Bulgaria', 'Morocco', 'Croatia', 'Guatemala', 'Lebanon', 'Costa Rica', 'Bolivia', 'Tunisia', 'Cuba', 'Ecuador', 'ARE', 'Uruguay', 'Panama', 'Mongolia', 'Nepal', 'Belarus', 'Latvia', 'Saudi Arabia', 'Azerbaijan', 'Paraguay', 'Bahrain', 'Sri Lanka', 'Kuwait', 'Dominican Republic', 'Cyprus', 'Myanmar', 'Palestine', 'Moldova', 'Estonia', 'Venezuela', 'Egypt', 'Libya', 'Qatar', 'Ethiopia', 'RÃ©union', 'Honduras', 'Armenia', 'Bosnia and Herzegovina', 'Oman', 'North Macedonia', 'Zambia', 'Kenya', 'Albania', 'Botswana', 'Luxembourg', 'Montenegro', 'Brunei', 'Algeria', 'Nigeria', 'Zimbabwe', 'Uzbekistan', 'Mozambique', 'Martinique', 'Laos', 'Afghanistan', 'Iceland', 'Kyrgyzstan', 'Guadeloupe', 'El Salvador', 'Trinidad and Tobago', 'Maldives', 'Ghana', 'Namibia', 'Uganda', 'Jamaica', 'Cambodia', 'Rwanda', 'Cameroon', 'Malta', 'Barbados', 'Angola', 'Channel Islands', 'French Guiana', 'COD', 'Senegal', 'Malawi', 'Ivory Coast', 'Suriname', 'New Caledonia', 'French Polynesia', 'Eswatini', 'Guyana', 'Belize', 'Fiji', 'Madagascar', 'Sudan', 'Mauritania', 'Cabo Verde', 'Bhutan', 'Syria', 'Burundi', 'Seychelles', 'Gabon', 'Andorra', 'Papua New Guinea', 'CuraÃ§ao', 'Aruba', 'Tanzania', 'Mayotte', 'Mauritius', 'Togo', 'Guinea', 'Isle of Man', 'Bahamas', 'Lesotho', 'Faeroe Islands', 'Haiti', 'Mali', 'Cayman Islands', 'Saint Lucia', 'Benin', 'Somalia', 'Micronesia', 'Congo', 'Solomon Islands', 'San Marino', 'Timor-Leste', 'Burkina Faso', 'Liechtenstein', 'Gibraltar', 'Grenada', 'Bermuda', 'Nicaragua', 'South Sudan', 'Tajikistan', 'Equatorial Guinea', 'Tonga', 'Samoa', 'Monaco', 'Marshall Islands', 'Dominica', 'Djibouti', 'CAF', 'Gambia', 'Saint Martin', 'Vanuatu', 'Greenland', 'Yemen', 'Caribbean Netherlands', 'Sint Maarten', 'Eritrea', 'Niger', 'St. Vincent Grenadines', 'Guinea-Bissau', 'Antigua and Barbuda', 'Comoros', 'Liberia', 'Sierra Leone', 'Chad', 'British Virgin Islands', 'Cook Islands', 'Saint Kitts and Nevis', 'Turks and Caicos', 'Sao Tome and Principe', 'Palau', 'St. Barth', 'Nauru', 'Kiribati', 'Anguilla', 'Macao', 'Saint Pierre Miquelon', 'Wallis and Futuna', 'Tuvalu', 'Saint Helena', 'Falkland Islands', 'Montserrat', 'Niue', 'Diamond Princess', 'Vatican City', 'Western Sahara', 'MS Zaandam', 'Tokelau', 'China']

In [63]:
import country_converter as coco
some_names = ['USA', 'India', 'France', 'Germany', 'Brazil', 'Japan', 'S. Korea', 'Italy', 'United Kingdom', 'Russia', 'Turkey', 'Spain', 'Vietnam', 'Australia', 'Taiwan', 'Argentina', 'Netherlands', 'Iran', 'Mexico', 'Indonesia', 'Poland', 'Colombia', 'Austria', 'Greece', 'Portugal', 'Ukraine', 'Chile', 'Malaysia', 'Israel', 'Belgium', 'DPRK', 'Thailand', 'Czechia', 'Canada', 'Peru', 'Switzerland', 'Philippines', 'South Africa', 'Romania', 'Denmark', 'Hong Kong', 'Sweden', 'Serbia', 'Iraq', 'New Zealand', 'Singapore', 'Hungary', 'Bangladesh', 'Slovakia', 'Georgia', 'Jordan', 'Ireland', 'Pakistan', 'Norway', 'Finland', 'Kazakhstan', 'Slovenia', 'Lithuania', 'Bulgaria', 'Morocco', 'Croatia', 'Guatemala', 'Lebanon', 'Costa Rica', 'Bolivia', 'Tunisia', 'Cuba', 'Ecuador', 'ARE', 'Uruguay', 'Panama', 'Mongolia', 'Nepal', 'Belarus', 'Latvia', 'Saudi Arabia', 'Azerbaijan', 'Paraguay', 'Bahrain', 'Sri Lanka', 'Kuwait', 'Dominican Republic', 'Cyprus', 'Myanmar', 'Palestine', 'Moldova', 'Estonia', 'Venezuela', 'Egypt', 'Libya', 'Qatar', 'Ethiopia', 'RÃ©union', 'Honduras', 'Armenia', 'Bosnia and Herzegovina', 'Oman', 'North Macedonia', 'Zambia', 'Kenya', 'Albania', 'Botswana', 'Luxembourg', 'Montenegro', 'Brunei', 'Algeria', 'Nigeria', 'Zimbabwe', 'Uzbekistan', 'Mozambique', 'Martinique', 'Laos', 'Afghanistan', 'Iceland', 'Kyrgyzstan', 'Guadeloupe', 'El Salvador', 'Trinidad and Tobago', 'Maldives', 'Ghana', 'Namibia', 'Uganda', 'Jamaica', 'Cambodia', 'Rwanda', 'Cameroon', 'Malta', 'Barbados', 'Angola', 'Channel Islands', 'French Guiana', 'COD', 'Senegal', 'Malawi', 'Ivory Coast', 'Suriname', 'New Caledonia', 'French Polynesia', 'Eswatini', 'Guyana', 'Belize', 'Fiji', 'Madagascar', 'Sudan', 'Mauritania', 'Cabo Verde', 'Bhutan', 'Syria', 'Burundi', 'Seychelles', 'Gabon', 'Andorra', 'Papua New Guinea', 'CuraÃ§ao', 'Aruba', 'Tanzania', 'Mayotte', 'Mauritius', 'Togo', 'Guinea', 'Isle of Man', 'Bahamas', 'Lesotho', 'Faeroe Islands', 'Haiti', 'Mali', 'Cayman Islands', 'Saint Lucia', 'Benin', 'Somalia', 'Micronesia', 'Congo', 'Solomon Islands', 'San Marino', 'Timor-Leste', 'Burkina Faso', 'Liechtenstein', 'Gibraltar', 'Grenada', 'Bermuda', 'Nicaragua', 'South Sudan', 'Tajikistan', 'Equatorial Guinea', 'Tonga', 'Samoa', 'Monaco', 'Marshall Islands', 'Dominica', 'Djibouti', 'CAF', 'Gambia', 'Saint Martin', 'Vanuatu', 'Greenland', 'Yemen', 'Caribbean Netherlands', 'Sint Maarten', 'Eritrea', 'Niger', 'St. Vincent Grenadines', 'Guinea-Bissau', 'Antigua and Barbuda', 'Comoros', 'Liberia', 'Sierra Leone', 'Chad', 'British Virgin Islands', 'Cook Islands', 'Saint Kitts and Nevis', 'Turks and Caicos', 'Sao Tome and Principe', 'Palau', 'St. Barth', 'Nauru', 'Kiribati', 'Anguilla', 'Macao', 'Saint Pierre Miquelon', 'Wallis and Futuna', 'Tuvalu', 'Saint Helena', 'Falkland Islands', 'Montserrat', 'Niue', 'Diamond Princess', 'Vatican City', 'Western Sahara', 'MS Zaandam', 'Tokelau', 'China']
standard_names = coco.convert(names=some_names, to='ISO3')
print(standard_names)

Channel Islands not found in regex
Diamond Princess not found in regex
MS Zaandam not found in regex

['USA', 'IND', 'FRA', 'DEU', 'BRA', 'JPN', 'KOR', 'ITA', 'GBR', 'RUS', 'TUR', 'ESP', 'VNM', 'AUS', 'TWN', 'ARG', 'NLD', 'IRN', 'MEX', 'IDN', 'POL', 'COL', 'AUT', 'GRC', 'PRT', 'UKR', 'CHL', 'MYS', 'ISR', 'BEL', 'PRK', 'THA', 'CZE', 'CAN', 'PER', 'CHE', 'PHL', 'ZAF', 'ROU', 'DNK', 'HKG', 'SWE', 'SRB', 'IRQ', 'NZL', 'SGP', 'HUN', 'BGD', 'SVK', 'GEO', 'JOR', 'IRL', 'PAK', 'NOR', 'FIN', 'KAZ', 'SVN', 'LTU', 'BGR', 'MAR', 'HRV', 'GTM', 'LBN', 'CRI', 'BOL', 'TUN', 'CUB', 'ECU', 'ARE', 'URY', 'PAN', 'MNG', 'NPL', 'BLR', 'LVA', 'SAU', 'AZE', 'PRY', 'BHR', 'LKA', 'KWT', 'DOM', 'CYP', 'MMR', 'PSE', 'MDA', 'EST', 'VEN', 'EGY', 'LBY', 'QAT', 'ETH', 'REU', 'HND', 'ARM', 'BIH', 'OMN', 'MKD', 'ZMB', 'KEN', 'ALB', 'BWA', 'LUX', 'MNE', 'BRN', 'DZA', 'NGA', 'ZWE', 'UZB', 'MOZ', 'MTQ', 'LAO', 'AFG', 'ISL', 'KGZ', 'GLP', 'SLV', 'TTO', 'MDV', 'GHA', 'NAM', 'UGA', 'JAM', 'KHM', 'RWA', 'CMR', 'MLT', 'BRB', 'AGO', 'not found', 'GUF', 'COD', 'SEN', 'MWI', 'CIV', 'SUR', 'NCL', 'PYF', 'SWZ', 'GUY', 'BLZ', 'FJI', 'MDG', 'SDN', 'MRT', 'CPV', 'BTN', 'SYR', 'BDI', 'SYC', 'GAB', 'AND', 'PNG', 'CUW', 'ABW', 'TZA', 'MYT', 'MUS', 'TGO', 'GIN', 'IMN', 'BHS', 'LSO', 'FRO', 'HTI', 'MLI', 'CYM', 'LCA', 'BEN', 'SOM', 'FSM', 'COG', 'SLB', 'SMR', 'TLS', 'BFA', 'LIE', 'GIB', 'GRD', 'BMU', 'NIC', 'SSD', 'TJK', 'GNQ', 'TON', 'WSM', 'MCO', 'MHL', 'DMA', 'DJI', 'CAF', 'GMB', 'MAF', 'VUT', 'GRL', 'YEM', 'BES', 'SXM', 'ERI', 'NER', 'VCT', 'GNB', 'ATG', 'COM', 'LBR', 'SLE', 'TCD', 'VGB', 'COK', 'KNA', 'TCA', 'STP', 'PLW', 'BLM', 'NRU', 'KIR', 'AIA', 'MAC', 'SPM', 'WLF', 'TUV', 'SHN', 'FLK', 'MSR', 'NIU', 'not found', 'VAT', 'ESH', 'not found', 'TKL', 'CHN']

#### erase the 3 "not found" cases by hand

In [64]:
isocode3 = ['USA', 'IND', 'FRA', 'DEU', 'BRA', 'JPN', 'KOR', 'ITA', 'GBR', 'RUS', 'TUR', 'ESP', 'VNM', 'AUS', 'TWN', 'ARG', 'NLD', 'IRN', 'MEX', 'IDN', 'POL', 'COL', 'AUT', 'GRC', 'PRT', 'UKR', 'CHL', 'MYS', 'ISR', 'BEL', 'PRK', 'THA', 'CZE', 'CAN', 'PER', 'CHE', 'PHL', 'ZAF', 'ROU', 'DNK', 'HKG', 'SWE', 'SRB', 'IRQ', 'NZL', 'SGP', 'HUN', 'BGD', 'SVK', 'GEO', 'JOR', 'IRL', 'PAK', 'NOR', 'FIN', 'KAZ', 'SVN', 'LTU', 'BGR', 'MAR', 'HRV', 'GTM', 'LBN', 'CRI', 'BOL', 'TUN', 'CUB', 'ECU', 'ARE', 'URY', 'PAN', 'MNG', 'NPL', 'BLR', 'LVA', 'SAU', 'AZE', 'PRY', 'BHR', 'LKA', 'KWT', 'DOM', 'CYP', 'MMR', 'PSE', 'MDA', 'EST', 'VEN', 'EGY', 'LBY', 'QAT', 'ETH', 'REU', 'HND', 'ARM', 'BIH', 'OMN', 'MKD', 'ZMB', 'KEN', 'ALB', 'BWA', 'LUX', 'MNE', 'BRN', 'DZA', 'NGA', 'ZWE', 'UZB', 'MOZ', 'MTQ', 'LAO', 'AFG', 'ISL', 'KGZ', 'GLP', 'SLV', 'TTO', 'MDV', 'GHA', 'NAM', 'UGA', 'JAM', 'KHM', 'RWA', 'CMR', 'MLT', 'BRB', 'AGO', 'GUF', 'COD', 'SEN', 'MWI', 'CIV', 'SUR', 'NCL', 'PYF', 'SWZ', 'GUY', 'BLZ', 'FJI', 'MDG', 'SDN', 'MRT', 'CPV', 'BTN', 'SYR', 'BDI', 'SYC', 'GAB', 'AND', 'PNG', 'CUW', 'ABW', 'TZA', 'MYT', 'MUS', 'TGO', 'GIN', 'IMN', 'BHS', 'LSO', 'FRO', 'HTI', 'MLI', 'CYM', 'LCA', 'BEN', 'SOM', 'FSM', 'COG', 'SLB', 'SMR', 'TLS', 'BFA', 'LIE', 'GIB', 'GRD', 'BMU', 'NIC', 'SSD', 'TJK', 'GNQ', 'TON', 'WSM', 'MCO', 'MHL', 'DMA', 'DJI', 'CAF', 'GMB', 'MAF', 'VUT', 'GRL', 'YEM', 'BES', 'SXM', 'ERI', 'NER', 'VCT', 'GNB', 'ATG', 'COM', 'LBR', 'SLE', 'TCD', 'VGB', 'COK', 'KNA', 'TCA', 'STP', 'PLW', 'BLM', 'NRU', 'KIR', 'AIA', 'MAC', 'SPM', 'WLF', 'TUV', 'SHN', 'FLK', 'MSR', 'NIU', 'VAT', 'ESH', 'TKL', 'CHN']

In [65]:
isocode3

['USA',
 'IND',
 'FRA',
 'DEU',
 'BRA',
 'JPN',
 'KOR',
 'ITA',
 'GBR',
 'RUS',
 'TUR',
 'ESP',
 'VNM',
 'AUS',
 'TWN',
 'ARG',
 'NLD',
 'IRN',
 'MEX',
 'IDN',
 'POL',
 'COL',
 'AUT',
 'GRC',
 'PRT',
 'UKR',
 'CHL',
 'MYS',
 'ISR',
 'BEL',
 'PRK',
 'THA',
 'CZE',
 'CAN',
 'PER',
 'CHE',
 'PHL',
 'ZAF',
 'ROU',
 'DNK',
 'HKG',
 'SWE',
 'SRB',
 'IRQ',
 'NZL',
 'SGP',
 'HUN',
 'BGD',
 'SVK',
 'GEO',
 'JOR',
 'IRL',
 'PAK',
 'NOR',
 'FIN',
 'KAZ',
 'SVN',
 'LTU',
 'BGR',
 'MAR',
 'HRV',
 'GTM',
 'LBN',
 'CRI',
 'BOL',
 'TUN',
 'CUB',
 'ECU',
 'ARE',
 'URY',
 'PAN',
 'MNG',
 'NPL',
 'BLR',
 'LVA',
 'SAU',
 'AZE',
 'PRY',
 'BHR',
 'LKA',
 'KWT',
 'DOM',
 'CYP',
 'MMR',
 'PSE',
 'MDA',
 'EST',
 'VEN',
 'EGY',
 'LBY',
 'QAT',
 'ETH',
 'REU',
 'HND',
 'ARM',
 'BIH',
 'OMN',
 'MKD',
 'ZMB',
 'KEN',
 'ALB',
 'BWA',
 'LUX',
 'MNE',
 'BRN',
 'DZA',
 'NGA',
 'ZWE',
 'UZB',
 'MOZ',
 'MTQ',
 'LAO',
 'AFG',
 'ISL',
 'KGZ',
 'GLP',
 'SLV',
 'TTO',
 'MDV',
 'GHA',
 'NAM',
 'UGA',
 'JAM',
 'KHM',
 'RWA',
 'CMR',
 'MLT',
 'BRB',
 'AGO',
 'GUF',
 'COD',
 'SEN',
 'MWI',
 'CIV',
 'SUR',
 'NCL',
 'PYF',
 'SWZ',
 'GUY',
 'BLZ',
 'FJI',
 'MDG',
 'SDN',
 'MRT',
 'CPV',
 'BTN',
 'SYR',
 'BDI',
 'SYC',
 'GAB',
 'AND',
 'PNG',
 'CUW',
 'ABW',
 'TZA',
 'MYT',
 'MUS',
 'TGO',
 'GIN',
 'IMN',
 'BHS',
 'LSO',
 'FRO',
 'HTI',
 'MLI',
 'CYM',
 'LCA',
 'BEN',
 'SOM',
 'FSM',
 'COG',
 'SLB',
 'SMR',
 'TLS',
 'BFA',
 'LIE',
 'GIB',
 'GRD',
 'BMU',
 'NIC',
 'SSD',
 'TJK',
 'GNQ',
 'TON',
 'WSM',
 'MCO',
 'MHL',
 'DMA',
 'DJI',
 'CAF',
 'GMB',
 'MAF',
 'VUT',
 'GRL',
 'YEM',
 'BES',
 'SXM',
 'ERI',
 'NER',
 'VCT',
 'GNB',
 'ATG',
 'COM',
 'LBR',
 'SLE',
 'TCD',
 'VGB',
 'COK',
 'KNA',
 'TCA',
 'STP',
 'PLW',
 'BLM',
 'NRU',
 'KIR',
 'AIA',
 'MAC',
 'SPM',
 'WLF',
 'TUV',
 'SHN',
 'FLK',
 'MSR',
 'NIU',
 'VAT',
 'ESH',
 'TKL',
 'CHN']

In [66]:
dfisocode3 = pd.DataFrame(isocode3)

In [67]:
dfisocode3

       0
0    USA
1    IND
2    FRA
3    DEU
4    BRA
..   ...
223  NIU
224  VAT
225  ESH
226  TKL
227  CHN

[228 rows x 1 columns]

In [68]:
dfisocode3.rename({0:'Country Code'}, axis = 'columns', inplace=True)

In [69]:
dfisocode3

    Country Code
0            USA
1            IND
2            FRA
3            DEU
4            BRA
..           ...
223          NIU
224          VAT
225          ESH
226          TKL
227          CHN

[228 rows x 1 columns]

In [70]:
covidcasesdeaths

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.0,0.9,"2,046"
3,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Vatican City,29,NaN,NaN,NaN,29,NaN,0,NaN,NaN,799,Europe,NaN,NaN,NaN
227,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,NaN,"626,161",Africa,NaN,NaN,NaN
228,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,Tokelau,5,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,"1,378",Australia/Oceania,NaN,NaN,"3,628"
230,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,"160,000,000","1,448,471,400",Asia,NaN,NaN,82

In [71]:
pd.set_option('display.max_rows', None)

In [72]:
dfisocode3.join(covidcasesdeaths)

,Country Code,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,IND,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,FRA,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,DEU,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,BRA,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,JPN,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,KOR,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,ITA,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,GBR,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,RUS,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,TUR,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,ESP,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,VNM,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,AUS,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,TWN,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,ARG,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,NLD,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,IRN,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,MEX,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,IDN,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,POL,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,COL,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,AUT,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,GRC,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,PRT,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,UKR,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,CHL,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,MYS,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,ISR,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,BEL,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,PRK,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,THA,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,CZE,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,CAN,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,PER,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,CHE,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,PHL,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,ZAF,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,ROU,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,DNK,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,HKG,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,SWE,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,SRB,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,IRQ,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,NZL,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,SGP,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,HUN,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,BGD,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,SVK,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,GEO,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,JOR,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,IRL,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,PAK,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,NOR,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,FIN,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,KAZ,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,SVN,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,LTU,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,BGR,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,MAR,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,HRV,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,GTM,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,LBN,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,CRI,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,BOL,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,TUN,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,CUB,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,ECU,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,URY,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,PAN,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,MNG,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,NPL,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,BLR,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,LVA,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,SAU,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,AZE,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,PRY,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,BHR,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,LKA,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,KWT,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,DOM,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,CYP,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,MMR,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,PSE,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,MDA,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,EST,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,VEN,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,EGY,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,LBY,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,QAT,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,ETH,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,REU,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,HND,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,ARM,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,BIH,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,OMN,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,MKD,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,ZMB,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,KEN,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,ALB,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,BWA,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,LUX,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,MNE,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,BRN,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,DZA,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,NGA,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,ZWE,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,UZB,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,MOZ,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,MTQ,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,LAO,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,AFG,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,ISL,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,KGZ,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,GLP,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,SLV,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,TTO,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,MDV,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,GHA,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,NAM,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,UGA,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,JAM,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,KHM,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,RWA,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,CMR,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,MLT,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,BRB,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,AGO,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,GUF,Channel Islands,"101,717",NaN,228,NaN,"101,321",NaN,168,NaN,"1,252,808","176,463",Europe,NaN,NaN,952
130,COD,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
131,SEN,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
132,MWI,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
133,CIV,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
134,SUR,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
135,NCL,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
136,PYF,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
137,SWZ,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
138,GUY,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
139,BLZ,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
140,FJI,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
141,MDG,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
142,SDN,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
143,MRT,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
144,CPV,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
145,BTN,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
146,SYR,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
147,BDI,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
148,SYC,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
149,GAB,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
150,AND,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
151,PNG,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
152,CUW,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
153,ABW,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
154,TZA,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
155,MYT,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
156,MUS,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
157,TGO,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
158,GIN,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
159,IMN,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
160,BHS,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
161,LSO,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
162,FRO,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
163,HTI,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
164,MLI,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
165,CYM,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
166,LCA,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
167,BEN,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
168,SOM,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
169,FSM,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
170,COG,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
171,SLB,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
172,SMR,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
173,TLS,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"

In [73]:
#129 is wrong GGY - Channel Islands

In [74]:
covidcasesdeaths[covidcasesdeaths['Country,Other'] != 'Channel Islands']

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
130,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
131,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
132,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
133,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
134,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
135,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
136,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
137,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
138,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
139,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
140,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
141,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
142,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
143,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
144,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
145,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
146,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
147,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
148,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
149,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
150,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
151,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
152,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
153,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
154,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
155,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
156,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
157,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
158,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
159,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
160,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
161,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
162,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
163,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
164,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
165,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
166,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
167,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
168,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
169,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
170,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
171,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
172,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
173,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
174,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
175,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3
176,Liechtenstein,"21,437",NaN,91,NaN,"21,345",NaN,1,NaN,"112,457","38,387",Europe,NaN,NaN,26
177,Gibraltar,"20,550",NaN,113,NaN,"16,579",NaN,"3,858",NaN,"534,283","33,704",Europe,NaN,NaN,"114,467"
178,Grenada,"19,680",NaN,238,NaN,"19,358",NaN,84,4,"182,981","113,475",North America,NaN,NaN,740
179,Bermuda,"18,860",NaN,165,NaN,"18,685",NaN,10,NaN,"1,029,558","61,939",North America,NaN,NaN,161
180,Nicaragua,"18,491",NaN,225,NaN,"4,225",NaN,"14,041",NaN,NaN,"6,779,100",North America,NaN,NaN,"2,071"
181,South Sudan,"18,368",NaN,138,NaN,"18,115",NaN,115,1,"410,280","11,618,511",Africa,NaN,NaN,10
182,Tajikistan,"17,786",NaN,125,NaN,"17,264",NaN,397,NaN,NaN,"9,957,464",Asia,NaN,NaN,40

In [75]:
covidcasesdeaths = covidcasesdeaths[covidcasesdeaths['Country,Other'] != 'Channel Islands']

In [76]:
covidcasesdeaths.reset_index(inplace=True,drop=True)

In [77]:
covidcasesdeaths

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
130,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
131,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
132,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
133,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
134,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
135,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
136,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
137,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
138,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
139,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
140,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
141,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
142,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
143,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
144,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
145,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
146,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
147,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
148,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
149,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
150,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
151,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
152,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
153,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
154,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
155,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
156,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
157,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
158,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
159,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
160,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
161,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
162,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
163,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
164,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
165,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
166,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
167,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
168,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
169,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
170,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
171,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
172,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
173,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
174,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3
175,Liechtenstein,"21,437",NaN,91,NaN,"21,345",NaN,1,NaN,"112,457","38,387",Europe,NaN,NaN,26
176,Gibraltar,"20,550",NaN,113,NaN,"16,579",NaN,"3,858",NaN,"534,283","33,704",Europe,NaN,NaN,"114,467"
177,Grenada,"19,680",NaN,238,NaN,"19,358",NaN,84,4,"182,981","113,475",North America,NaN,NaN,740
178,Bermuda,"18,860",NaN,165,NaN,"18,685",NaN,10,NaN,"1,029,558","61,939",North America,NaN,NaN,161
179,Nicaragua,"18,491",NaN,225,NaN,"4,225",NaN,"14,041",NaN,NaN,"6,779,100",North America,NaN,NaN,"2,071"
180,South Sudan,"18,368",NaN,138,NaN,"18,115",NaN,115,1,"410,280","11,618,511",Africa,NaN,NaN,10
181,Tajikistan,"17,786",NaN,125,NaN,"17,264",NaN,397,NaN,NaN,"9,957,464",Asia,NaN,NaN,40

In [78]:
dfisocode3.join(covidcasesdeaths)

,Country Code,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,IND,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,FRA,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,DEU,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,BRA,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,JPN,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,KOR,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,ITA,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,GBR,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,RUS,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,TUR,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,ESP,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,VNM,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,AUS,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,TWN,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,ARG,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,NLD,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,IRN,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,MEX,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,IDN,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,POL,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,COL,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,AUT,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,GRC,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,PRT,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,UKR,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,CHL,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,MYS,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,ISR,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,BEL,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,PRK,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,THA,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,CZE,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,CAN,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,PER,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,CHE,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,PHL,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,ZAF,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,ROU,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,DNK,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,HKG,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,SWE,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,SRB,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,IRQ,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,NZL,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,SGP,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,HUN,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,BGD,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,SVK,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,GEO,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,JOR,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,IRL,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,PAK,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,NOR,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,FIN,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,KAZ,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,SVN,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,LTU,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,BGR,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,MAR,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,HRV,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,GTM,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,LBN,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,CRI,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,BOL,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,TUN,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,CUB,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,ECU,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,URY,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,PAN,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,MNG,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,NPL,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,BLR,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,LVA,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,SAU,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,AZE,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,PRY,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,BHR,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,LKA,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,KWT,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,DOM,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,CYP,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,MMR,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,PSE,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,MDA,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,EST,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,VEN,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,EGY,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,LBY,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,QAT,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,ETH,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,REU,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,HND,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,ARM,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,BIH,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,OMN,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,MKD,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,ZMB,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,KEN,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,ALB,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,BWA,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,LUX,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,MNE,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,BRN,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,DZA,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,NGA,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,ZWE,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,UZB,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,MOZ,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,MTQ,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,LAO,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,AFG,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,ISL,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,KGZ,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,GLP,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,SLV,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,TTO,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,MDV,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,GHA,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,NAM,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,UGA,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,JAM,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,KHM,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,RWA,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,CMR,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,MLT,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,BRB,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,AGO,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,GUF,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
130,COD,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
131,SEN,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
132,MWI,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
133,CIV,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
134,SUR,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
135,NCL,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
136,PYF,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
137,SWZ,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
138,GUY,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
139,BLZ,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
140,FJI,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
141,MDG,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
142,SDN,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
143,MRT,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
144,CPV,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
145,BTN,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
146,SYR,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
147,BDI,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
148,SYC,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
149,GAB,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
150,AND,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
151,PNG,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
152,CUW,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
153,ABW,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
154,TZA,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
155,MYT,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
156,MUS,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
157,TGO,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
158,GIN,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
159,IMN,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
160,BHS,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
161,LSO,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
162,FRO,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
163,HTI,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
164,MLI,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
165,CYM,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
166,LCA,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
167,BEN,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
168,SOM,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
169,FSM,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
170,COG,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
171,SLB,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
172,SMR,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
173,TLS,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
174,BFA,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3

In [79]:
#224 wrong Diamond Princess

In [80]:
covidcasesdeaths = covidcasesdeaths[covidcasesdeaths['Country,Other'] != 'Diamond Princess']

In [81]:
covidcasesdeaths.reset_index(inplace=True,drop=True)

In [82]:
covidcasesdeaths

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
130,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
131,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
132,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
133,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
134,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
135,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
136,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
137,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
138,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
139,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
140,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
141,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
142,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
143,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
144,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
145,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
146,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
147,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
148,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
149,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
150,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
151,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
152,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
153,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
154,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
155,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
156,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
157,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
158,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
159,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
160,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
161,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
162,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
163,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
164,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
165,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
166,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
167,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
168,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
169,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
170,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
171,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
172,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
173,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
174,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3
175,Liechtenstein,"21,437",NaN,91,NaN,"21,345",NaN,1,NaN,"112,457","38,387",Europe,NaN,NaN,26
176,Gibraltar,"20,550",NaN,113,NaN,"16,579",NaN,"3,858",NaN,"534,283","33,704",Europe,NaN,NaN,"114,467"
177,Grenada,"19,680",NaN,238,NaN,"19,358",NaN,84,4,"182,981","113,475",North America,NaN,NaN,740
178,Bermuda,"18,860",NaN,165,NaN,"18,685",NaN,10,NaN,"1,029,558","61,939",North America,NaN,NaN,161
179,Nicaragua,"18,491",NaN,225,NaN,"4,225",NaN,"14,041",NaN,NaN,"6,779,100",North America,NaN,NaN,"2,071"
180,South Sudan,"18,368",NaN,138,NaN,"18,115",NaN,115,1,"410,280","11,618,511",Africa,NaN,NaN,10
181,Tajikistan,"17,786",NaN,125,NaN,"17,264",NaN,397,NaN,NaN,"9,957,464",Asia,NaN,NaN,40

In [83]:
dfisocode3.join(covidcasesdeaths)

,Country Code,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,IND,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,FRA,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,DEU,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,BRA,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,JPN,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,KOR,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,ITA,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,GBR,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,RUS,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,TUR,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,ESP,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,VNM,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,AUS,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,TWN,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,ARG,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,NLD,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,IRN,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,MEX,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,IDN,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,POL,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,COL,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,AUT,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,GRC,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,PRT,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,UKR,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,CHL,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,MYS,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,ISR,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,BEL,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,PRK,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,THA,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,CZE,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,CAN,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,PER,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,CHE,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,PHL,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,ZAF,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,ROU,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,DNK,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,HKG,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,SWE,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,SRB,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,IRQ,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,NZL,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,SGP,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,HUN,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,BGD,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,SVK,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,GEO,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,JOR,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,IRL,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,PAK,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,NOR,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,FIN,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,KAZ,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,SVN,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,LTU,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,BGR,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,MAR,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,HRV,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,GTM,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,LBN,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,CRI,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,BOL,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,TUN,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,CUB,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,ECU,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,URY,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,PAN,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,MNG,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,NPL,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,BLR,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,LVA,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,SAU,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,AZE,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,PRY,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,BHR,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,LKA,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,KWT,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,DOM,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,CYP,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,MMR,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,PSE,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,MDA,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,EST,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,VEN,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,EGY,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,LBY,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,QAT,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,ETH,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,REU,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,HND,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,ARM,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,BIH,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,OMN,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,MKD,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,ZMB,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,KEN,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,ALB,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,BWA,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,LUX,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,MNE,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,BRN,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,DZA,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,NGA,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,ZWE,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,UZB,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,MOZ,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,MTQ,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,LAO,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,AFG,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,ISL,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,KGZ,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,GLP,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,SLV,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,TTO,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,MDV,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,GHA,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,NAM,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,UGA,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,JAM,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,KHM,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,RWA,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,CMR,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,MLT,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,BRB,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,AGO,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,GUF,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
130,COD,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
131,SEN,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
132,MWI,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
133,CIV,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
134,SUR,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
135,NCL,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
136,PYF,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
137,SWZ,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
138,GUY,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
139,BLZ,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
140,FJI,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
141,MDG,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
142,SDN,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
143,MRT,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
144,CPV,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
145,BTN,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
146,SYR,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
147,BDI,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
148,SYC,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
149,GAB,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
150,AND,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
151,PNG,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
152,CUW,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
153,ABW,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
154,TZA,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
155,MYT,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
156,MUS,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
157,TGO,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
158,GIN,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
159,IMN,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
160,BHS,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
161,LSO,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
162,FRO,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
163,HTI,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
164,MLI,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
165,CYM,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
166,LCA,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
167,BEN,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
168,SOM,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
169,FSM,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
170,COG,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
171,SLB,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
172,SMR,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
173,TLS,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
174,BFA,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3

In [84]:
#226 MS Zaandam wrong

In [85]:
covidcasesdeaths = covidcasesdeaths[covidcasesdeaths['Country,Other'] != 'MS Zaandam']

In [86]:
covidcasesdeaths.reset_index(inplace=True,drop=True)

In [87]:
dfisocode3.join(covidcasesdeaths)

,Country Code,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,IND,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,FRA,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,DEU,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,BRA,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,JPN,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,KOR,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,ITA,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,GBR,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,RUS,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,TUR,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,ESP,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,VNM,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,AUS,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,TWN,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,ARG,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,NLD,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,IRN,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,MEX,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,IDN,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,POL,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,COL,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,AUT,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,GRC,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,PRT,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,UKR,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,CHL,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,MYS,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,ISR,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,BEL,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,PRK,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,THA,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,CZE,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,CAN,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,PER,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,CHE,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,PHL,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,ZAF,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,ROU,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,DNK,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,HKG,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,SWE,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,SRB,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,IRQ,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,NZL,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,SGP,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,HUN,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,BGD,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,SVK,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,GEO,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,JOR,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,IRL,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,PAK,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,NOR,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,FIN,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,KAZ,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,SVN,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,LTU,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,BGR,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,MAR,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,HRV,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,GTM,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,LBN,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,CRI,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,BOL,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,TUN,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,CUB,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,ECU,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,URY,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,PAN,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,MNG,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,NPL,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,BLR,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,LVA,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,SAU,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,AZE,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,PRY,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,BHR,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,LKA,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,KWT,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,DOM,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,CYP,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,MMR,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,PSE,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,MDA,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,EST,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,VEN,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,EGY,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,LBY,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,QAT,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,ETH,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,REU,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,HND,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,ARM,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,BIH,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,OMN,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,MKD,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,ZMB,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,KEN,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,ALB,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,BWA,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,LUX,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,MNE,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,BRN,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,DZA,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,NGA,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,ZWE,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,UZB,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,MOZ,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,MTQ,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,LAO,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,AFG,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,ISL,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,KGZ,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,GLP,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,SLV,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,TTO,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,MDV,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,GHA,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,NAM,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,UGA,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,JAM,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,KHM,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,RWA,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,CMR,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,MLT,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,BRB,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,AGO,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,GUF,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
130,COD,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
131,SEN,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
132,MWI,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
133,CIV,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
134,SUR,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
135,NCL,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
136,PYF,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
137,SWZ,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
138,GUY,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
139,BLZ,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
140,FJI,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
141,MDG,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
142,SDN,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
143,MRT,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
144,CPV,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
145,BTN,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
146,SYR,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
147,BDI,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
148,SYC,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
149,GAB,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
150,AND,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
151,PNG,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
152,CUW,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
153,ABW,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
154,TZA,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
155,MYT,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
156,MUS,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
157,TGO,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
158,GIN,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
159,IMN,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
160,BHS,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
161,LSO,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
162,FRO,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
163,HTI,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
164,MLI,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
165,CYM,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
166,LCA,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
167,BEN,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
168,SOM,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
169,FSM,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
170,COG,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
171,SLB,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
172,SMR,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
173,TLS,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
174,BFA,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3

In [88]:
covidcasesdeathsisocode = dfisocode3.join(covidcasesdeaths)

In [89]:
covidcasesdeathsisocode

,Country Code,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,USA,"106,273,691",NaN,"1,155,668",NaN,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
1,IND,India,"44,733,719",NaN,"530,916",NaN,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
2,FRA,France,"39,817,657","+9,922","165,794",58.0,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
3,DEU,Germany,"38,363,343",NaN,"171,169",NaN,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
4,BRA,Brazil,"37,319,254",NaN,"700,556",NaN,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
5,JPN,Japan,"33,491,480","+9,500","74,002",21.0,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
6,KOR,S. Korea,"30,871,740","+14,465","34,296",7.0,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
7,ITA,Italy,"25,695,311",NaN,"189,089",NaN,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
8,GBR,United Kingdom,"24,448,729",NaN,"209,396",NaN,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
9,RUS,Russia,"22,679,739","+8,636","397,420",36.0,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
10,TUR,Turkey,"17,042,722",NaN,"101,492",NaN,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
11,ESP,Spain,"13,798,747",NaN,"120,426",NaN,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
12,VNM,Vietnam,"11,527,454",+51,"43,186",NaN,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
13,AUS,Australia,"11,327,773",NaN,"19,856",NaN,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
14,TWN,Taiwan,"10,239,998",NaN,"19,005",NaN,"10,178,415","+10,187","42,578",NaN,"30,742,304","23,888,595",Asia,NaN,NaN,"1,782"
15,ARG,Argentina,"10,044,957",NaN,"130,472",NaN,"9,914,485",NaN,0,363,"35,716,069","46,010,234",South America,NaN,NaN,NaN
16,NLD,Netherlands,"8,610,372",NaN,"22,992",NaN,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
17,IRN,Iran,"7,585,422",NaN,"145,220",NaN,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
18,MEX,Mexico,"7,547,892","+2,913","333,555",13.0,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
19,IDN,Indonesia,"6,748,973",+665,"161,039",4.0,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
20,POL,Poland,"6,500,971","+1,240","119,391",13.0,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
21,COL,Colombia,"6,362,312",NaN,"142,678",NaN,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
22,AUT,Austria,"6,041,470","+1,751","22,157",NaN,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
23,GRC,Greece,"5,951,892",NaN,"36,517",NaN,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
24,PRT,Portugal,"5,575,030",NaN,"26,408",NaN,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
25,UKR,Ukraine,"5,445,979",NaN,"111,558",NaN,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
26,CHL,Chile,"5,269,112","+1,485","64,497",NaN,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
27,MYS,Malaysia,"5,052,337",NaN,"36,982",NaN,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
28,ISR,Israel,"4,815,175",NaN,"12,404",NaN,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
29,BEL,Belgium,"4,776,837",NaN,"34,059",NaN,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
30,PRK,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,NaN,"25,990,679",Asia,NaN,NaN,NaN
31,THA,Thailand,"4,728,799",NaN,"33,938",NaN,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
32,CZE,Czechia,"4,635,346",+452,"42,683",3.0,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
33,CAN,Canada,"4,634,277",NaN,"52,121",NaN,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
34,PER,Peru,"4,494,028",NaN,"219,837",NaN,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
35,CHE,Switzerland,"4,397,632",NaN,"14,452",NaN,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
36,PHL,Philippines,"4,082,580",+176,"66,396",6.0,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
37,ZAF,South Africa,"4,074,814",+259,"102,595",NaN,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
38,ROU,Romania,"3,374,825",NaN,"67,917",NaN,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
39,DNK,Denmark,"3,178,740",+91,"8,407",3.0,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
40,HKG,Hong Kong,"2,885,246",+99,"13,482",5.0,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
41,SWE,Sweden,"2,701,192",NaN,"23,823",NaN,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
42,SRB,Serbia,"2,521,017",NaN,"17,980",NaN,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
43,IRQ,Iraq,"2,465,545",NaN,"25,375",NaN,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
44,NZL,New Zealand,"2,274,370",NaN,"4,015",NaN,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
45,SGP,Singapore,"2,255,812",NaN,"1,722",NaN,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
46,HUN,Hungary,"2,199,764",+618,"48,811",8.0,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
47,BGD,Bangladesh,"2,038,014",NaN,"29,446",NaN,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
48,SVK,Slovakia,"1,865,664",+80,"21,115",1.0,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
49,GEO,Georgia,"1,833,502",NaN,"17,019",NaN,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
50,JOR,Jordan,"1,746,997",NaN,"14,122",NaN,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
51,IRL,Ireland,"1,707,466",NaN,"8,763",NaN,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
52,PAK,Pakistan,"1,579,911",+49,"30,650",NaN,"1,538,689",NaN,"10,572",24,"30,570,862","229,488,994",Asia,0.20,NaN,46
53,NOR,Norway,"1,481,421",NaN,"5,213",NaN,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
54,FIN,Finland,"1,466,778",NaN,"9,054",NaN,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
55,KAZ,Kazakhstan,"1,410,158",+73,"13,848",NaN,"1,383,020",NaN,"13,290",24,"11,575,012","19,205,043",Asia,4.00,NaN,692
56,SVN,Slovenia,"1,341,726",+166,"7,100",NaN,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
57,LTU,Lithuania,"1,315,338",+269,"9,642",1.0,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
58,BGR,Bulgaria,"1,300,621",NaN,"38,269",NaN,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
59,MAR,Morocco,"1,272,622",NaN,"16,296",NaN,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
60,HRV,Croatia,"1,270,891",NaN,"18,069",NaN,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
61,GTM,Guatemala,"1,245,365",NaN,"20,188",NaN,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
62,LBN,Lebanon,"1,235,065",+68,"10,873",1.0,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
63,CRI,Costa Rica,"1,222,661",NaN,"9,309",NaN,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
64,BOL,Bolivia,"1,196,031",+50,"22,375",1.0,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
65,TUN,Tunisia,"1,152,033",NaN,"29,363",NaN,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
66,CUB,Cuba,"1,112,870",+17,"8,530",NaN,"1,104,234",+11,106,2,"14,324,663","11,305,652",North America,2.00,NaN,9
67,ECU,Ecuador,"1,059,009",NaN,"36,017",NaN,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
68,ARE,ARE,"1,058,240",NaN,"2,349",NaN,"1,039,300",NaN,"16,591",NaN,"199,873,980","10,081,785",Asia,NaN,NaN,"1,646"
69,URY,Uruguay,"1,036,159",NaN,"7,621",NaN,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
70,PAN,Panama,"1,033,781",NaN,"8,612",NaN,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
71,MNG,Mongolia,"1,007,911",NaN,"2,179",NaN,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
72,NPL,Nepal,"1,001,605",+71,"12,020",NaN,"989,263",+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11
73,BLR,Belarus,"994,037",NaN,"7,118",NaN,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
74,LVA,Latvia,"977,030",+41,"6,290",2.0,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
75,SAU,Saudi Arabia,"835,224",+399,"9,632",1.0,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
76,AZE,Azerbaijan,"829,955",NaN,"10,189",NaN,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
77,PRY,Paraguay,"808,943",NaN,"19,902",NaN,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
78,BHR,Bahrain,"717,479",+143,"1,559",NaN,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
79,LKA,Sri Lanka,"672,084",+1,"16,834",NaN,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
80,KWT,Kuwait,"665,122",NaN,"2,570",NaN,"660,237",NaN,"2,315",NaN,"8,455,743","4,380,326",Asia,NaN,NaN,528
81,DOM,Dominican Republic,"660,937",NaN,"4,384",NaN,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
82,CYP,Cyprus,"655,664",NaN,"1,349",NaN,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
83,MMR,Myanmar,"634,087",+1,"19,490",NaN,"614,566",+3,31,NaN,"10,193,914","55,227,143",Asia,0.02,NaN,0.6
84,PSE,Palestine,"621,008",NaN,"5,404",NaN,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
85,MDA,Moldova,"618,827",NaN,"12,086",NaN,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
86,EST,Estonia,"616,829",NaN,"2,971",NaN,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
87,VEN,Venezuela,"552,454",NaN,"5,856",NaN,"546,289",NaN,309,31,"3,359,014","29,266,991",South America,NaN,NaN,11
88,EGY,Egypt,"515,882",NaN,"24,613",NaN,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
89,LBY,Libya,"507,206",NaN,"6,437",NaN,"500,764",NaN,5,NaN,"2,483,848","7,040,745",Africa,NaN,NaN,0.7
90,QAT,Qatar,"501,236",+345,689,NaN,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
91,ETH,Ethiopia,"500,659",+21,"7,573",NaN,"487,690",+7,"5,396",1,"5,523,562","120,812,698",Africa,0.20,NaN,45
92,REU,RÃ©union,"486,588",NaN,921,NaN,"418,572",NaN,"67,095",10,"1,603,660","908,061",Africa,NaN,NaN,"73,888"
93,HND,Honduras,"472,467",NaN,"11,111",NaN,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
94,ARM,Armenia,"448,151",NaN,"8,739",NaN,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
95,BIH,Bosnia and Herzegovina,"402,076",NaN,"16,306",NaN,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
96,OMN,Oman,"399,449",NaN,"4,628",NaN,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
97,MKD,North Macedonia,"347,492",NaN,"9,666",NaN,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
98,ZMB,Zambia,"343,687",NaN,"4,058",NaN,"339,507",NaN,122,NaN,"3,994,061","19,470,234",Africa,NaN,NaN,6
99,KEN,Kenya,"342,970",NaN,"5,688",NaN,"337,243",NaN,39,1,"3,967,062","56,215,221",Africa,NaN,NaN,0.7
100,ALB,Albania,"334,663",NaN,"3,602",NaN,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
101,BWA,Botswana,"329,812",NaN,"2,801",NaN,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
102,LUX,Luxembourg,"297,757",NaN,"1,133",NaN,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
103,MNE,Montenegro,"290,296",+61,"2,816",NaN,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
104,BRN,Brunei,"283,345",NaN,225,NaN,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
105,DZA,Algeria,"271,599",+5,"6,881",NaN,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
106,NGA,Nigeria,"266,660",NaN,"3,155",NaN,"259,938",NaN,"3,567",11,"5,708,974","216,746,934",Africa,NaN,NaN,16
107,ZWE,Zimbabwe,"264,511",NaN,"5,679",NaN,"258,484",NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23
108,UZB,Uzbekistan,"251,839",NaN,"1,637",NaN,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
109,MOZ,Mozambique,"233,334",NaN,"2,242",NaN,"228,805",NaN,"2,287",11,"1,371,127","33,089,461",Africa,NaN,NaN,69
110,MTQ,Martinique,"229,807",NaN,"1,098",NaN,NaN,NaN,NaN,12,"828,928","374,087",North America,NaN,NaN,"611,101"
111,LAO,Laos,"218,037",NaN,758,NaN,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"
112,AFG,Afghanistan,"211,144",+136,"7,896",NaN,"192,354",+11,"10,894",45,"1,218,351","40,754,388",Asia,3.00,NaN,267
113,ISL,Iceland,"209,191",NaN,229,NaN,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
114,KGZ,Kyrgyzstan,"206,805",NaN,"2,991",NaN,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
115,GLP,Guadeloupe,"202,058",NaN,"1,010",NaN,NaN,NaN,NaN,19,"938,039","399,794",North America,NaN,NaN,"497,251"
116,SLV,El Salvador,"201,785",NaN,"4,230",NaN,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
117,TTO,Trinidad and Tobago,"191,007",NaN,"4,372",NaN,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
118,MDV,Maldives,"185,810",NaN,311,NaN,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
119,GHA,Ghana,"171,527",NaN,"1,462",NaN,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
120,NAM,Namibia,"171,222",NaN,"4,090",NaN,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
121,UGA,Uganda,"170,570",NaN,"3,630",NaN,"100,431",NaN,"66,509",3,"3,012,408","48,432,863",Africa,NaN,NaN,"1,373"
122,JAM,Jamaica,"154,602",NaN,"3,529",NaN,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
123,KHM,Cambodia,"138,726",NaN,"3,056",NaN,"135,666",NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2
124,RWA,Rwanda,"133,194",NaN,"1,468",NaN,"131,647",NaN,79,NaN,"6,021,981","13,600,464",Africa,NaN,NaN,6
125,CMR,Cameroon,"124,741",NaN,"1,968",NaN,"122,640",NaN,133,13,"1,751,774","27,911,548",Africa,NaN,NaN,5
126,MLT,Malta,"118,133",NaN,832,NaN,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
127,BRB,Barbados,"107,332",NaN,582,NaN,"106,739",NaN,11,NaN,"799,983","288,023",North America,NaN,NaN,38
128,AGO,Angola,"105,316",NaN,"1,933",NaN,"103,342",NaN,41,NaN,"1,499,795","35,027,343",Africa,NaN,NaN,1
129,GUF,French Guiana,"98,041",NaN,420,NaN,"11,254",NaN,"86,367",6,"651,257","314,169",South America,NaN,NaN,"274,906"
130,COD,COD,"95,895",NaN,"1,464",NaN,"84,395",NaN,"10,036",NaN,"846,704","95,240,792",Africa,NaN,NaN,105
131,SEN,Senegal,"88,970",NaN,"1,971",NaN,"86,967",NaN,32,NaN,"1,146,543","17,653,671",Africa,NaN,NaN,2
132,MWI,Malawi,"88,711",NaN,"2,686",NaN,"85,619",NaN,406,67,"624,784","20,180,839",Africa,NaN,NaN,20
133,CIV,Ivory Coast,"88,304",NaN,834,NaN,"87,465",NaN,5,NaN,"1,686,095","27,742,298",Africa,NaN,NaN,0.2
134,SUR,Suriname,"82,495",NaN,"1,404",NaN,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
135,NCL,New Caledonia,"79,916",NaN,314,NaN,"79,596",NaN,6,9,"98,964","290,915",Australia/Oceania,NaN,NaN,21
136,PYF,French Polynesia,"78,153",NaN,649,NaN,NaN,NaN,NaN,7,NaN,"284,164",Australia/Oceania,NaN,NaN,"154,854"
137,SWZ,Eswatini,"74,323",NaN,"1,425",NaN,"72,824",NaN,74,NaN,"1,048,704","1,184,817",Africa,NaN,NaN,62
138,GUY,Guyana,"73,120",NaN,"1,298",NaN,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
139,BLZ,Belize,"70,782",NaN,688,NaN,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
140,FJI,Fiji,"68,914",NaN,883,NaN,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
141,MDG,Madagascar,"68,105",NaN,"1,424",NaN,"66,566",NaN,115,NaN,"528,968","29,178,077",Africa,NaN,NaN,4
142,SDN,Sudan,"63,922",NaN,"5,034",NaN,"58,603",NaN,285,NaN,"562,941","45,992,020",Africa,NaN,NaN,6
143,MRT,Mauritania,"63,668",NaN,997,NaN,"62,441",NaN,230,NaN,"1,009,957","4,901,981",Africa,NaN,NaN,47
144,CPV,Cabo Verde,"63,260",NaN,413,NaN,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
145,BTN,Bhutan,"62,648",NaN,21,NaN,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
146,SYR,Syria,"57,498",NaN,"3,164",NaN,"54,334",NaN,0,NaN,"146,269","19,364,809",Asia,NaN,NaN,NaN
147,BDI,Burundi,"53,686",NaN,38,NaN,"53,569",NaN,79,NaN,"345,742","12,624,840",Africa,NaN,NaN,6
148,SYC,Seychelles,"50,937",NaN,172,NaN,"50,750",NaN,15,NaN,NaN,"99,426",Africa,NaN,NaN,151
149,GAB,Gabon,"48,981",NaN,306,NaN,"48,674",NaN,1,NaN,"1,621,909","2,331,533",Africa,NaN,NaN,0.4
150,AND,Andorra,"47,917",NaN,165,NaN,"47,563",NaN,189,14,"249,838","77,463",Europe,NaN,NaN,"2,440"
151,PNG,Papua New Guinea,"46,835",NaN,670,NaN,"43,982",NaN,"2,183",7,"249,149","9,292,169",Australia/Oceania,NaN,NaN,235
152,CUW,CuraÃ§ao,"45,986",NaN,295,NaN,"44,720",NaN,971,3,"496,693","165,529",North America,NaN,NaN,"5,866"
153,ABW,Aruba,"44,082",NaN,236,NaN,"42,438",NaN,"1,408",2,"177,885","107,609",North America,NaN,NaN,"13,084"
154,TZA,Tanzania,"42,942",NaN,846,NaN,NaN,NaN,NaN,7,NaN,"63,298,550",Africa,NaN,NaN,662
155,MYT,Mayotte,"42,007",NaN,188,NaN,NaN,NaN,NaN,NaN,"176,919","286,259",Africa,NaN,NaN,"135,734"
156,MUS,Mauritius,"41,849",NaN,"1,043",NaN,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
157,TGO,Togo,"39,450",NaN,290,NaN,"39,127",NaN,33,NaN,"809,755","8,680,837",Africa,NaN,NaN,4
158,GIN,Guinea,"38,280",NaN,467,NaN,"37,757",NaN,56,8,"660,107","13,865,691",Africa,NaN,NaN,4
159,IMN,Isle of Man,"38,008",NaN,116,NaN,NaN,NaN,NaN,NaN,"150,753","85,732",Europe,NaN,NaN,"129,450"
160,BHS,Bahamas,"37,491",NaN,833,NaN,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
161,LSO,Lesotho,"34,790",NaN,723,NaN,"25,980",NaN,"8,087",NaN,"431,221","2,175,699",Africa,NaN,NaN,"3,717"
162,FRO,Faeroe Islands,"34,658",NaN,28,NaN,NaN,NaN,NaN,5,"778,000","49,233",Europe,NaN,NaN,"547,133"
163,HTI,Haiti,"34,217",NaN,860,NaN,"33,148",NaN,209,NaN,"132,422","11,680,283",North America,NaN,NaN,18
164,MLI,Mali,"33,118",NaN,743,NaN,"32,295",NaN,80,NaN,"801,612","21,473,764",Africa,NaN,NaN,4
165,CYM,Cayman Islands,"31,472",NaN,37,NaN,"8,553",NaN,"22,882",1,"222,773","67,277",North America,NaN,NaN,"340,116"
166,LCA,Saint Lucia,"30,028",NaN,409,NaN,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
167,BEN,Benin,"27,999",NaN,163,NaN,"27,830",NaN,6,NaN,"604,310","12,784,726",Africa,NaN,NaN,0.5
168,SOM,Somalia,"27,334",NaN,"1,361",NaN,"13,182",NaN,"12,791",NaN,"400,466","16,841,795",Africa,NaN,NaN,759
169,FSM,Micronesia,"25,703",NaN,63,NaN,NaN,NaN,NaN,1,"54,967","117,489",Australia/Oceania,NaN,NaN,"155,104"
170,COG,Congo,"25,375",NaN,386,NaN,"24,006",NaN,983,NaN,"347,815","5,797,805",Africa,NaN,NaN,170
171,SLB,Solomon Islands,"24,575",NaN,153,NaN,NaN,NaN,NaN,1,NaN,"721,159",Australia/Oceania,NaN,NaN,"11,183"
172,SMR,San Marino,"23,849",NaN,123,NaN,"23,689",NaN,37,4,"196,855","34,085",Europe,NaN,NaN,"1,086"
173,TLS,Timor-Leste,"23,423",NaN,138,NaN,"23,102",NaN,183,NaN,"278,529","1,369,429",Asia,NaN,NaN,134
174,BFA,Burkina Faso,"22,056",NaN,396,NaN,"21,596",NaN,64,NaN,"248,995","22,102,838",Africa,NaN,NaN,3

### 4.4 Merging the (Economic Indicators and Covid Vaccines) with Covid Cases/Deaths

#### final merge covidcasesdeathsisocode with economicindicatorsvaccines

In [90]:
covid = economicindicatorsvaccines.merge(covidcasesdeathsisocode, on = 'Country Code', indicator = '_merge1')

In [91]:
covid

,Country Code,Country,HDI rank,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GDP 2021 (US$),GDP per capita 2021 (US$),...,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,_merge1
0,CHE,Switzerland,1,0.962,83.9872,16.500299,13.859660,66933.004540,8.006402e+11,91991.600458,...,NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755,both
1,NOR,Norway,2,0.961,83.2339,18.185200,13.003630,64660.106220,4.821749e+11,89154.276093,...,NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248,both
2,ISL,Iceland,3,0.959,82.6782,19.163059,13.767170,55782.049810,2.560242e+10,68727.636665,...,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871",both
3,HKG,"Hong Kong, China (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,3.691764e+11,49800.542414,...,+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249,both
4,AUS,Australia,5,0.951,84.5265,21.054590,12.726820,49238.433350,1.552667e+12,60443.109165,...,NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674",both
5,DNK,Denmark,6,0.948,81.3753,18.714800,12.960490,60364.785950,3.983033e+11,68007.756673,...,+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273,both
6,SWE,Sweden,7,0.947,82.9833,19.418530,12.609720,54489.374010,6.356638e+11,61028.738060,...,+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225,both
7,IRL,Ireland,8,0.945,81.9976,18.945221,11.582223,76168.984430,5.041826e+11,100172.079253,...,NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720,both
8,DEU,Germany,9,0.942,80.6301,17.010139,14.090967,54534.216820,4.259935e+12,51203.554473,...,"+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045",both
9,NLD,Netherlands,10,0.941,81.6873,18.693165,12.581630,55979.411000,1.012847e+12,57767.878811,...,NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708,both
10,FIN,Finland,11,0.940,82.0381,19.051929,12.873620,49452.166720,2.973019e+11,53654.750296,...,+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489,both
11,SGP,Singapore,12,0.939,82.7545,16.524321,11.924880,90918.644710,3.969869e+11,72794.003023,...,NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583",both
12,BEL,Belgium,13,0.937,81.8787,19.604219,12.375680,52293.399770,5.941042e+11,51247.014353,...,"+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778",both
13,NZL,New Zealand,13,0.937,82.4513,20.283890,12.944690,44057.313940,2.498857e+11,48781.026633,...,NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214",both
14,CAN,Canada,15,0.936,82.6565,16.396259,13.834427,46807.986190,1.988336e+12,51987.939053,...,NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845,both
15,LUX,Luxembourg,17,0.930,82.6287,14.398140,13.015192,84649.474670,8.550624e+10,133590.146976,...,NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883",both
16,GBR,United Kingdom,18,0.929,80.7422,17.309719,13.406120,45224.765640,3.131378e+12,46510.282782,...,"+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320,both
17,JPN,Japan,19,0.925,84.7839,15.221626,13.366100,42274.291340,4.940878e+12,39312.660373,...,+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128",both
18,KOR,Korea (Republic of),19,0.925,83.6978,16.521740,12.512930,44500.931870,1.810956e+12,34997.781643,...,"+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536",both
19,USA,United States,21,0.921,77.1982,16.280979,13.683430,64765.215090,2.331508e+13,70248.629000,...,NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173",both
20,ISR,Israel,22,0.919,82.2550,16.050890,13.344866,41523.743190,4.885265e+11,52170.711862,...,NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874,both
21,MLT,Malta,23,0.918,83.7769,16.838570,12.210260,38884.456230,1.736404e+10,33486.671984,...,NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486",both
22,SVN,Slovenia,23,0.918,80.6904,17.654921,12.803680,39746.019870,6.174859e+10,29291.400623,...,NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186",both
23,AUT,Austria,25,0.916,81.5797,16.007959,12.256690,53618.671380,4.803684e+11,53637.705711,...,"+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270",both
24,ESP,Spain,27,0.905,83.0100,17.916901,10.605400,38353.601640,1.427381e+12,30103.513733,...,NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693,both
25,FRA,France,28,0.903,82.4988,15.812070,11.610060,45937.052730,2.957880e+12,43658.978978,...,"+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046",both
26,CYP,Cyprus,29,0.896,81.2033,15.648270,12.440170,38188.421520,2.840787e+10,31551.816406,...,NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679",both
27,ITA,Italy,30,0.895,82.8502,16.226789,10.740110,42839.514410,2.107703e+12,35657.497563,...,NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218",both
28,EST,Estonia,31,0.890,77.1436,15.928960,13.548430,38048.263720,3.719117e+10,27943.701220,...,NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227",both
29,CZE,Czechia,32,0.889,77.7283,16.219681,12.869310,38745.213860,2.817779e+11,26821.245228,...,+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554,both
30,GRC,Greece,33,0.887,80.1106,20.028790,11.408530,29002.485450,2.148739e+11,20192.596304,...,"+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178",both
31,POL,Poland,34,0.876,76.4572,16.027149,13.164750,33033.960810,6.794448e+11,17999.909950,...,NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707",both
32,BHR,Bahrain,35,0.875,78.7605,16.297560,11.046590,39497.247880,3.886866e+10,26562.969135,...,+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447,both
33,LTU,Lithuania,35,0.875,73.7201,16.285061,13.498100,37931.303590,6.644526e+10,23723.340251,...,+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966",both
34,SAU,Saudi Arabia,35,0.875,76.9360,16.135490,11.310530,46111.551350,8.335412e+11,23185.870792,...,+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151,both
35,PRT,Portugal,38,0.866,81.0443,16.871229,9.575940,33154.533430,2.536631e+11,24567.509265,...,NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449,both
36,LVA,Latvia,39,0.863,73.5786,16.202530,13.252720,32803.234230,3.985350e+10,21148.162941,...,+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248,both
37,HRV,Croatia,40,0.858,77.5804,15.112100,12.191084,30132.288140,6.895508e+10,17685.325283,...,NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121,both
38,CHL,Chile,42,0.855,78.9435,16.731300,10.934966,24563.244860,3.170585e+11,16265.095977,...,"+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157,both
39,QAT,Qatar,42,0.855,79.2716,12.637220,9.996011,87134.134690,1.796772e+11,66838.357433,...,+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488,both
40,SVK,Slovakia,45,0.848,74.9101,14.513040,12.911420,30690.485520,1.165271e+11,21391.925334,...,+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153,both
41,HUN,Hungary,46,0.846,74.5301,15.033628,12.249590,32789.010630,1.818480e+11,18728.121895,...,+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443,both
42,TUR,TÃ¼rkiye,48,0.838,76.0324,18.338221,8.633140,31032.801060,8.190352e+11,9661.235975,...,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819",both
43,MNE,Montenegro,49,0.832,76.3426,15.081610,12.176483,20838.801290,5.861268e+09,9465.703999,...,+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081",both
44,BRN,Brunei Darussalam,51,0.829,74.6424,13.951780,9.180000,64489.539540,1.400657e+10,31449.076562,...,NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721",both
45,RUS,Russian Federation,52,0.822,69.4190,15.766370,12.774288,27166.308910,1.778783e+12,12194.777344,...,"+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597",both
46,ROU,Romania,53,0.821,74.1847,14.229900,11.275120,30027.291310,2.840876e+11,14858.229429,...,"+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787,both
47,OMN,Oman,54,0.816,72.5406,14.573490,11.654040,27054.325050,8.819198e+10,19509.466463,...,NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907",both
48,BHS,Bahamas,55,0.812,71.5983,12.899450,12.641924,30486.184290,1.120860e+10,27478.389629,...,NaN,292,1,"257,839","400,516",North America,NaN,NaN,729,both
49,TTO,Trinidad and Tobago,57,0.810,72.9709,14.535453,11.610624,23392.020840,2.446020e+10,16032.502768,...,NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58,both
50,CRI,Costa Rica,58,0.809,77.0232,16.545771,8.804060,19974.273580,6.428244e+10,12472.443729,...,NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046",both
51,URY,Uruguay,58,0.809,75.4356,16.832600,8.982550,21268.881220,5.931948e+10,17313.188348,...,NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174,both
52,BLR,Belarus,60,0.808,72.4380,15.169970,12.143580,18848.967040,6.820538e+10,7302.257794,...,NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141,both
53,PAN,Panama,61,0.805,76.2233,13.057879,10.540590,26956.837070,6.360510e+10,14617.604482,...,NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246,both
54,MYS,Malaysia,62,0.803,74.8839,13.343040,10.645060,26657.943550,3.729810e+11,11109.261839,...,NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341,both
55,GEO,Georgia,63,0.802,71.6940,15.568520,12.822220,14664.168250,1.862937e+10,5023.274380,...,NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062",both
56,MUS,Mauritius,63,0.802,73.5552,15.173530,10.427910,22025.346310,1.152904e+10,9106.237202,...,NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530,both
57,SRB,Serbia,63,0.802,74.1923,14.400090,11.369870,19123.027470,6.308205e+10,9230.178316,...,NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636",both
58,THA,Thailand,66,0.800,78.7154,15.882219,8.697120,17030.153520,5.059470e+11,7066.190546,...,NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32,both
59,ALB,Albania,67,0.796,76.4626,14.448000,11.286455,14131.110390,1.825579e+10,6492.872012,...,NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596,both
60,BGR,Bulgaria,68,0.795,71.7980,13.897290,11.413180,23078.955950,8.405631e+10,12221.496606,...,NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387,both
61,LKA,Sri Lanka,73,0.782,76.3991,14.139905,10.827300,12578.220550,8.892726e+10,4013.687657,...,+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7,both
62,BIH,Bosnia and Herzegovina,74,0.780,75.3003,13.800000,10.536320,15241.914650,2.336536e+10,7143.310548,...,NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058",both
63,IRN,Iran (Islamic Republic of),76,0.774,73.8749,14.615250,10.636453,13000.711700,3.597132e+11,4091.209187,...,NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136",both
64,UKR,Ukraine,77,0.773,71.6240,14.956569,11.131420,13255.509770,2.000855e+11,4835.571777,...,NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787,both
65,MKD,North Macedonia,78,0.770,73.8415,13.624432,10.228150,15917.752830,1.382505e+10,6694.641126,...,NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364,both
66,CHN,China,79,0.768,78.2107,14.236115,7.600118,17504.399690,1.773406e+13,12556.333120,...,NaN,"118,977",NaN,"160,000,000","1,448,471,400",Asia,NaN,NaN,82,both
67,DOM,Dominican Republic,80,0.767,72.6146,14.466558,9.306864,17989.600370,9.424345e+10,8476.752157,...,NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064",both
68,MDA,Moldova (Republic of),80,0.767,68.8459,14.433000,11.821590,14875.331890,1.367922e+10,5230.661733,...,NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566",both
69,PER,Peru,84,0.762,72.3769,15.387734,9.885519,12245.893660,2.232495e+11,6621.574336,...,NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116,both
70,ARM,Armenia,85,0.759,72.0431,13.116760,11.330300,13157.993900,1.386141e+10,4966.513471,...,NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430",both
71,MEX,Mexico,86,0.758,70.2127,14.864440,9.221050,17896.294980,1.272839e+12,10045.680500,...,"+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238",both
72,BRA,Brazil,87,0.754,72.7504,15.599060,8.128814,14369.888480,1.608981e+12,7507.160971,...,NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716",both
73,COL,Colombia,88,0.752,72.8296,14.442750,8.862860,14384.356660,3.144641e+11,6104.136709,...,NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659,both
74,VCT,Saint Vincent and the Grenadines,89,0.751,69.6291,14.672206,10.833430,11961.087920,9.041815e+08,8666.387041,...,NaN,5,NaN,"113,886","111,551",North America,NaN,NaN,45,both
75,MDV,Maldives,90,0.747,79.9182,12.635610,7.322000,15448.127880,5.405576e+09,10366.293358,...,NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319",both
76,DZA,Algeria,91,0.745,76.3767,14.626896,8.069284,10800.225460,1.630444e+11,3690.627878,...,NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804",both
77,AZE,Azerbaijan,91,0.745,69.3658,13.496890,10.542970,14256.744560,5.462218e+10,5387.997975,...,NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44,both
78,TON,Tonga,91,0.745,70.9857,16.048571,11.392594,6822.031250,4.692313e+08,4426.000637,...,NaN,"1,163",NaN,"535,009","107,749",Australia/Oceania,NaN,NaN,"10,794",both
79,ECU,Ecuador,95,0.740,73.6700,14.624230,8.817120,10311.632730,1.061659e+11,5965.132871,...,NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77,both
80,MNG,Mongolia,96,0.739,70.9754,14.980350,9.423700,10588.225320,1.528644e+10,4566.140154,...,NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1,both
81,EGY,Egypt,97,0.731,70.2207,13.786500,9.573026,11731.690560,4.041428e+11,3698.834981,...,NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462,both
82,TUN,Tunisia,97,0.731,73.7719,15.425382,7.431599,10257.544770,4.668674e+10,3807.139150,...,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052",both
83,FJI,Fiji,99,0.730,67.1140,14.736790,10.921548,9980.110866,4.296305e+09,4646.612723,...,NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118",both
84,SUR,Suriname,99,0.730,70.2743,13.035644,9.776801,12672.200330,2.984706e+09,4869.134226,...,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502",both
85,UZB,Uzbekistan,101,0.727,70.8616,12.477140,11.895590,7916.785725,6.923890e+10,1983.064723,...,NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254,both
86,JOR,Jordan,102,0.720,74.2563,10.646560,10.446680,9923.714974,4.574427e+10,4103.258966,...,NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181,both
87,PRY,Paraguay,105,0.717,70.2617,12.987991,8.861840,12349.286000,3.949543e+10,5891.499965,...,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418",both
88,PSE,"Palestine, State of",106,0.715,73.4727,13.358010,9.938480,6582.899416,1.803680e+10,3663.969055,...,NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30,both
89,LCA,Saint Lucia,106,0.715,71.1114,12.866110,8.545040,12048.303810,1.691275e+09,9414.226231,...,NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831",both
90,GUY,Guyana,108,0.714,65.6734,12.502722,8.617477,22464.657340,8.044499e+09,9998.544311,...,NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5,both
91,ZAF,South Africa,109,0.713,62.3410,13.643710,11.373160,12948.373250,4.190150e+11,7055.044776,...,NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983,both
92,JAM,Jamaica,110,0.709,70.5003,13.404920,9.154629,8834.475670,1.465759e+10,5183.581305,...,NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227",both
93,WSM,Samoa,111,0.707,72.7675,12.418859,11.403800,5307.953374,8.438424e+08,3857.318464,...,NaN,"15,101",NaN,"187,397","202,239",Australia/Oceania,NaN,NaN,"74,669",both
94,LBN,Lebanon,112,0.706,75.0472,11.285870,8.718636,9525.831467,2.313194e+10,4136.146347,...,NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435",both
95,IDN,Indonesia,114,0.705,67.5703,13.748894,8.556510,11466.068360,1.186093e+12,4332.709281,...,+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21,both
96,VNM,Viet Nam,115,0.703,73.6181,12.951932,8.370280,7867.371345,3.661376e+11,3756.489121,...,+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784",both
97,PHL,Philippines,116,0.699,69.2664,13.126570,8.969100,8920.428468,3.940864e+11,3460.530963,...,+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81,both
98,BWA,Botswana,117,0.693,61.1409,12.265138,10.340000,16198.318410,1.761479e+10,6805.221274,...,NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17,both
99,BOL,Bolivia (Plurinational State of),118,0.692,63.6304,14.946971,9.827750,8111.190194,4.040821e+10,3345.196589,...,+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759,both
100,KGZ,Kyrgyzstan,118,0.692,69.9774,13.195300,11.374106,4566.303831,8.543424e+09,1276.700365,...,NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101",both
101,IRQ,Iraq,121,0.686,70.3779,12.087473,7.905593,9977.249073,2.078893e+11,4775.377454,...,NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16,both
102,BLZ,Belize,123,0.683,70.4697,12.991690,8.847600,6309.099778,2.491500e+09,6228.267309,...,NaN,9,6,"576,016","412,190",North America,NaN,NaN,22,both
103,MAR,Morocco,123,0.683,74.0419,14.151910,5.916000,7302.819170,1.428663e+11,3795.380127,...,NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5,both
104,SLV,El Salvador,125,0.675,70.7479,12.671348,7.150930,8295.665889,2.873694e+10,4551.184661,...,NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770",both
105,NIC,Nicaragua,126,0.667,73.8368,12.641358,7.144000,5624.793595,1.401302e+10,2045.535402,...,NaN,"14,041",NaN,NaN,"6,779,100",North America,NaN,NaN,"2,071",both
106,BTN,Bhutan,127,0.666,71.8150,13.225005,5.170262,9437.541512,2.539553e+09,3266.364905,...,NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349",both
107,CPV,Cabo Verde,128,0.662,74.0518,12.554614,6.287719,6230.200199,1.936174e+09,3293.233054,...,NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107,both
108,BGD,Bangladesh,129,0.661,72.3811,12.441980,7.379060,5472.104781,4.162649e+11,2457.924880,...,NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60,both
109,IND,India,132,0.633,67.2398,11.874620,6.655109,6589.980037,3.176295e+12,2256.590409,...,NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16,both
110,GHA,Ghana,133,0.632,63.7954,12.047780,8.329887,5744.504017,7.759428e+10,2363.299296,...,NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2,both
111,GTM,Guatemala,135,0.627,69.2368,10.562450,5.681300,8723.285317,8.598575e+10,5025.542291,...,NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55,both
112,HND,Honduras,137,0.621,70.1229,10.132814,7.088480,5297.955301,2.848867e+10,2771.717461,...,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169",both
113,NAM,Namibia,139,0.615,59.2690,11.927207,7.192013,8633.504452,1.231060e+10,4865.557765,...,NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13,both
114,LAO,Lao People's Democratic Republic,140,0.607,68.0608,10.136110,5.374000,7699.579617,1.882715e+10,2535.623432,...,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020",both
115,VUT,Vanuatu,140,0.607,70.4490,11.535315,7.064846,3085.411633,9.563327e+08,2996.621062,...,NaN,24,NaN,"24,976","321,832",Australia/Oceania,NaN,NaN,75,both
116,NPL,Nepal,143,0.602,68.4495,12.886950,5.121793,3877.315444,3.628883e+10,1208.218534,...,+28,322,NaN,"6,022,060","30,225,582",Asia,2.00,NaN,11,both
117,KHM,Cambodia,146,0.593,69.5835,11.467720,5.088000,4078.697154,2.696106e+10,1625.235020,...,NaN,4,NaN,"3,091,420","17,168,639",Asia,NaN,NaN,0.2,both
118,ZWE,Zimbabwe,146,0.593,59.2531,12.110969,8.710909,3809.887158,2.837124e+10,1773.920411,...,NaN,348,12,"2,525,756","15,331,428",Africa,NaN,NaN,23,both

In [92]:
covid.shape

(149, 41)

In [93]:
covid = covid.drop(['_merge1'], axis=1)

In [94]:
covid

,Country Code,Country,HDI rank,Human Development Index 2021 (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GDP 2021 (US$),GDP per capita 2021 (US$),...,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,CHE,Switzerland,1,0.962,83.9872,16.500299,13.859660,66933.004540,8.006402e+11,91991.600458,...,"4,376,555",NaN,"6,625",39,"23,833,472","8,773,637",Europe,NaN,NaN,755
1,NOR,Norway,2,0.961,83.2339,18.185200,13.003630,64660.106220,4.821749e+11,89154.276093,...,"1,474,840",NaN,"1,368",20,"11,002,430","5,511,370",Europe,NaN,NaN,248
2,ISL,Iceland,3,0.959,82.6782,19.163059,13.767170,55782.049810,2.560242e+10,68727.636665,...,NaN,NaN,NaN,2,"1,996,384","345,393",Europe,NaN,NaN,"385,871"
3,HKG,"Hong Kong, China (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,3.691764e+11,49800.542414,...,"2,869,869",+96,"1,895",28,"76,127,725","7,604,299",Asia,13.00,0.70,249
4,AUS,Australia,5,0.951,84.5265,21.054590,12.726820,49238.433350,1.552667e+12,60443.109165,...,"11,264,265",NaN,"43,652",33,"78,835,048","26,068,792",Australia/Oceania,NaN,NaN,"1,674"
5,DNK,Denmark,6,0.948,81.3753,18.714800,12.960490,60364.785950,3.983033e+11,68007.756673,...,"3,168,739",+152,"1,594",19,"129,244,268","5,834,950",Europe,16.00,0.50,273
6,SWE,Sweden,7,0.947,82.9833,19.418530,12.609720,54489.374010,6.356638e+11,61028.738060,...,"2,675,072",+56,"2,297",8,"19,500,873","10,218,971",Europe,NaN,NaN,225
7,IRL,Ireland,8,0.945,81.9976,18.945221,11.582223,76168.984430,5.041826e+11,100172.079253,...,"1,695,087",NaN,"3,616",12,"13,076,646","5,020,199",Europe,NaN,NaN,720
8,DEU,Germany,9,0.942,80.6301,17.010139,14.090967,54534.216820,4.259935e+12,51203.554473,...,"38,104,500","+6,900","87,674",NaN,"122,332,384","83,883,596",Europe,NaN,NaN,"1,045"
9,NLD,Netherlands,10,0.941,81.6873,18.693165,12.581630,55979.411000,1.012847e+12,57767.878811,...,"8,575,190",NaN,"12,190",53,"25,984,435","17,211,447",Europe,NaN,NaN,708
10,FIN,Finland,11,0.940,82.0381,19.051929,12.873620,49452.166720,2.973019e+11,53654.750296,...,"1,455,010",+112,"2,714",21,"12,069,254","5,554,960",Europe,NaN,NaN,489
11,SGP,Singapore,12,0.939,82.7545,16.524321,11.924880,90918.644710,3.969869e+11,72794.003023,...,"2,149,583",NaN,"104,507",1,"24,756,666","5,943,546",Asia,NaN,NaN,"17,583"
12,BEL,Belgium,13,0.937,81.8787,19.604219,12.375680,52293.399770,5.941042e+11,51247.014353,...,"4,698,695","+1,653","44,083",43,"36,921,180","11,668,278",Europe,NaN,NaN,"3,778"
13,NZL,New Zealand,13,0.937,82.4513,20.283890,12.944690,44057.313940,2.498857e+11,48781.026633,...,"2,259,509",NaN,"10,846",NaN,"7,768,604","4,898,203",Australia/Oceania,NaN,NaN,"2,214"
14,CAN,Canada,15,0.936,82.6565,16.396259,13.834427,46807.986190,1.988336e+12,51987.939053,...,"4,549,731",NaN,"32,425",99,"66,343,123","38,388,419",North America,NaN,NaN,845
15,LUX,Luxembourg,17,0.930,82.6287,14.398140,13.015192,84649.474670,8.550624e+10,133590.146976,...,"288,991",NaN,"7,633",NaN,"4,412,567","642,371",Europe,NaN,NaN,"11,883"
16,GBR,United Kingdom,18,0.929,80.7422,17.309719,13.406120,45224.765640,3.131378e+12,46510.282782,...,"24,217,438","+4,283","21,895",NaN,"522,526,476","68,497,907",Europe,NaN,NaN,320
17,JPN,Japan,19,0.925,84.7839,15.221626,13.366100,42274.291340,4.940878e+12,39312.660373,...,"21,722,070",+328,"11,695,408",56,"98,452,116","125,584,838",Asia,76.00,0.20,"93,128"
18,KOR,Korea (Republic of),19,0.925,83.6978,16.521740,12.512930,44500.931870,1.810956e+12,34997.781643,...,"30,655,934","+8,987","181,510",126,"15,804,065","51,329,899",Asia,282.00,0.10,"3,536"
19,USA,United States,21,0.921,77.1982,16.280979,13.683430,64765.215090,2.331508e+13,70248.629000,...,"104,055,782",NaN,"1,062,241","1,895","1,174,878,661","334,805,269",North America,NaN,NaN,"3,173"
20,ISR,Israel,22,0.919,82.2550,16.050890,13.344866,41523.743190,4.885265e+11,52170.711862,...,"4,794,621",NaN,"8,150",57,"41,373,364","9,326,000",Asia,NaN,NaN,874
21,MLT,Malta,23,0.918,83.7769,16.838570,12.210260,38884.456230,1.736404e+10,33486.671984,...,"116,641",NaN,660,4,"2,127,851","444,033",Europe,NaN,NaN,"1,486"
22,SVN,Slovenia,23,0.918,80.6904,17.654921,12.803680,39746.019870,6.174859e+10,29291.400623,...,"1,328,006",NaN,"6,620",8,"2,847,701","2,078,034",Europe,80.00,NaN,"3,186"
23,AUT,Austria,25,0.916,81.5797,16.007959,12.256690,53618.671380,4.803684e+11,53637.705711,...,"5,998,735","+2,365","20,578",55,"211,273,524","9,066,710",Europe,193.00,NaN,"2,270"
24,ESP,Spain,27,0.905,83.0100,17.916901,10.605400,38353.601640,1.427381e+12,30103.513733,...,"13,645,949",NaN,"32,372",231,"471,036,328","46,719,142",Europe,NaN,NaN,693
25,FRA,France,28,0.903,82.4988,15.812070,11.610060,45937.052730,2.957880e+12,43658.978978,...,"39,517,646","+16,280","134,217",869,"271,490,188","65,584,518",Europe,151.00,0.90,"2,046"
26,CYP,Cyprus,29,0.896,81.2033,15.648270,12.440170,38188.421520,2.840787e+10,31551.816406,...,"651,037",NaN,"3,278",60,"9,640,118","1,223,387",Asia,NaN,NaN,"2,679"
27,ITA,Italy,30,0.895,82.8502,16.226789,10.740110,42839.514410,2.107703e+12,35657.497563,...,"25,372,554",NaN,"133,668",84,"270,012,027","60,262,770",Europe,NaN,NaN,"2,218"
28,EST,Estonia,31,0.890,77.1436,15.928960,13.548430,38048.263720,3.719117e+10,27943.701220,...,"524,990",NaN,"88,868",3,"3,693,746","1,321,910",Europe,NaN,NaN,"67,227"
29,CZE,Czechia,32,0.889,77.7283,16.219681,12.869310,38745.213860,2.817779e+11,26821.245228,...,"4,586,718",+93,"5,945",43,"57,127,316","10,736,784",Europe,42.00,0.30,554
30,GRC,Greece,33,0.887,80.1106,20.028790,11.408530,29002.485450,2.148739e+11,20192.596304,...,"5,892,901","+4,495","22,474",115,"102,228,365","10,316,637",Europe,NaN,NaN,"2,178"
31,POL,Poland,34,0.876,76.4572,16.027149,13.164750,33033.960810,6.794448e+11,17999.909950,...,"5,335,940",NaN,"1,045,640",696,"38,555,058","37,739,785",Europe,33.00,0.30,"27,707"
32,BHR,Bahrain,35,0.875,78.7605,16.297560,11.046590,39497.247880,3.886866e+10,26562.969135,...,"715,123",+95,797,2,"10,799,671","1,783,983",Asia,80.00,NaN,447
33,LTU,Lithuania,35,0.875,73.7201,16.285061,13.498100,37931.303590,6.644526e+10,23723.340251,...,"1,300,462",+383,"5,234",5,"10,419,935","2,661,708",Europe,101.00,0.40,"1,966"
34,SAU,Saudi Arabia,35,0.875,76.9360,16.135490,11.310530,46111.551350,8.335412e+11,23185.870792,...,"820,193",+393,"5,399",74,"45,316,590","35,844,909",Asia,11.00,0.03,151
35,PRT,Portugal,38,0.866,81.0443,16.871229,9.575940,33154.533430,2.536631e+11,24567.509265,...,"5,544,065",NaN,"4,557",61,"46,052,812","10,140,570",Europe,NaN,NaN,449
36,LVA,Latvia,39,0.863,73.5786,16.202530,13.252720,32803.234230,3.985350e+10,21148.162941,...,"970,282",+34,458,13,"7,870,315","1,848,837",Europe,22.00,1.00,248
37,HRV,Croatia,40,0.858,77.5804,15.112100,12.191084,30132.288140,6.895508e+10,17685.325283,...,"1,252,329",NaN,493,4,"5,553,846","4,059,286",Europe,NaN,NaN,121
38,CHL,Chile,42,0.855,78.9435,16.731300,10.934966,24563.244860,3.170585e+11,16265.095977,...,"5,201,598","+2,993","3,017",84,"49,096,959","19,250,195",South America,77.00,NaN,157
39,QAT,Qatar,42,0.855,79.2716,12.637220,9.996011,87134.134690,1.796772e+11,66838.357433,...,"499,092",+169,"1,455",48,"4,065,369","2,979,915",Asia,116.00,NaN,488
40,SVK,Slovakia,45,0.848,74.9101,14.513040,12.911420,30690.485520,1.165271e+11,21391.925334,...,"1,843,713",+84,836,17,"7,419,720","5,460,193",Europe,15.00,0.20,153
41,HUN,Hungary,46,0.846,74.5301,15.033628,12.249590,32789.010630,1.818480e+11,18728.121895,...,"2,146,693",+690,"4,260",3,"11,394,556","9,606,259",Europe,64.00,0.80,443
42,TUR,TÃ¼rkiye,48,0.838,76.0324,18.338221,8.633140,31032.801060,8.190352e+11,9661.235975,...,NaN,NaN,NaN,NaN,"162,743,369","85,561,976",Asia,NaN,NaN,"1,819"
43,MNE,Montenegro,49,0.832,76.3426,15.081610,12.176483,20838.801290,5.861268e+09,9465.703999,...,"286,801",+60,679,6,"2,736,615","627,950",Europe,97.00,NaN,"1,081"
44,BRN,Brunei Darussalam,51,0.829,74.6424,13.951780,9.180000,64489.539540,1.400657e+10,31449.076562,...,"243,601",NaN,"39,519",3,"717,784","445,431",Asia,NaN,NaN,"88,721"
45,RUS,Russian Federation,52,0.822,69.4190,15.766370,12.774288,27166.308910,1.778783e+12,12194.777344,...,"22,049,429","+11,807","232,890",NaN,"273,400,000","145,805,947",Europe,59.00,0.20,"1,597"
46,ROU,Romania,53,0.821,74.1847,14.229900,11.275120,30027.291310,2.840876e+11,14858.229429,...,"3,291,922","+7,483","14,986",134,"27,060,823","19,031,335",Europe,NaN,NaN,787
47,OMN,Oman,54,0.816,72.5406,14.573490,11.654040,27054.325050,8.819198e+10,19509.466463,...,"384,669",NaN,"10,152",2,"25,000,000","5,323,993",Asia,NaN,NaN,"1,907"
48,BHS,Bahamas,55,0.812,71.5983,12.899450,12.641924,30486.184290,1.120860e+10,27478.389629,...,"36,366",NaN,292,1,"257,839","400,516",North America,NaN,NaN,729
49,TTO,Trinidad and Tobago,57,0.810,72.9709,14.535453,11.610624,23392.020840,2.446020e+10,16032.502768,...,"186,554",NaN,81,8,"907,114","1,406,585",North America,NaN,NaN,58
50,CRI,Costa Rica,58,0.809,77.0232,16.545771,8.804060,19974.273580,6.428244e+10,12472.443729,...,"860,711",NaN,"352,641",52,"4,659,757","5,182,354",North America,NaN,NaN,"68,046"
51,URY,Uruguay,58,0.809,75.4356,16.832600,8.982550,21268.881220,5.931948e+10,17313.188348,...,"1,027,930",NaN,608,18,"6,114,822","3,496,016",South America,NaN,NaN,174
52,BLR,Belarus,60,0.808,72.4380,15.169970,12.143580,18848.967040,6.820538e+10,7302.257794,...,"985,592",NaN,"1,327",NaN,"13,646,641","9,432,800",Europe,NaN,NaN,141
53,PAN,Panama,61,0.805,76.2233,13.057879,10.540590,26956.837070,6.360510e+10,14617.604482,...,"1,024,076",NaN,"1,093",16,"7,594,428","4,446,964",North America,NaN,NaN,246
54,MYS,Malaysia,62,0.803,74.8839,13.343040,10.645060,26657.943550,3.729810e+11,11109.261839,...,"5,004,043",NaN,"11,312",13,"68,335,643","33,181,072",Asia,NaN,NaN,341
55,GEO,Georgia,63,0.802,71.6940,15.568520,12.822220,14664.168250,1.862937e+10,5023.274380,...,"1,776,548",NaN,"39,935",NaN,"16,920,079","3,968,738",Asia,NaN,NaN,"10,062"
56,MUS,Mauritius,63,0.802,73.5552,15.173530,10.427910,22025.346310,1.152904e+10,9106.237202,...,"40,131",NaN,675,NaN,"358,675","1,274,727",Africa,NaN,NaN,530
57,SRB,Serbia,63,0.802,74.1923,14.400090,11.369870,19123.027470,6.308205e+10,9230.178316,...,"2,488,882",NaN,"14,155",12,"12,648,684","8,653,016",Europe,NaN,NaN,"1,636"
58,THA,Thailand,66,0.800,78.7154,15.882219,8.697120,17030.153520,5.059470e+11,7066.190546,...,"4,692,636",NaN,"2,225",NaN,"17,270,775","70,078,203",Asia,NaN,NaN,32
59,ALB,Albania,67,0.796,76.4626,14.448000,11.286455,14131.110390,1.825579e+10,6492.872012,...,"329,352",NaN,"1,709",NaN,"1,941,032","2,866,374",Europe,NaN,NaN,596
60,BGR,Bulgaria,68,0.795,71.7980,13.897290,11.413180,23078.955950,8.405631e+10,12221.496606,...,"1,259,702",NaN,"2,650",38,"11,130,747","6,844,597",Europe,NaN,NaN,387
61,LKA,Sri Lanka,73,0.782,76.3991,14.139905,10.827300,12578.220550,8.892726e+10,4013.687657,...,"655,234",+1,16,NaN,"6,486,117","21,575,842",Asia,0.05,NaN,0.7
62,BIH,Bosnia and Herzegovina,74,0.780,75.3003,13.800000,10.536320,15241.914650,2.336536e+10,7143.310548,...,"379,084",NaN,"6,686",NaN,"1,884,721","3,249,317",Europe,NaN,NaN,"2,058"
63,IRN,Iran (Islamic Republic of),76,0.774,73.8749,14.615250,10.636453,13000.711700,3.597132e+11,4091.209187,...,"7,342,490",NaN,"97,712",407,"55,353,767","86,022,837",Asia,NaN,NaN,"1,136"
64,UKR,Ukraine,77,0.773,71.6240,14.956569,11.131420,13255.509770,2.000855e+11,4835.571777,...,"5,300,430",NaN,"33,991",NaN,"32,603,805","43,192,122",Europe,NaN,NaN,787
65,MKD,North Macedonia,78,0.770,73.8415,13.624432,10.228150,15917.752830,1.382505e+10,6694.641126,...,"337,068",NaN,758,NaN,"2,226,216","2,081,304",Europe,NaN,NaN,364
66,CHN,China,79,0.768,78.2107,14.236115,7.600118,17504.399690,1.773406e+13,12556.333120,...,"379,053",NaN,"118,977",NaN,"160,000,000","1,448,471,400",Asia,NaN,NaN,82
67,DOM,Dominican Republic,80,0.767,72.6146,14.466558,9.306864,17989.600370,9.424345e+10,8476.752157,...,"644,785",NaN,"11,768",4,"3,740,928","11,056,370",North America,NaN,NaN,"1,064"
68,MDA,Moldova (Republic of),80,0.767,68.8459,14.433000,11.821590,14875.331890,1.367922e+10,5230.661733,...,"504,142",NaN,"102,599",49,"3,216,305","4,013,171",Europe,NaN,NaN,"25,566"
69,PER,Peru,84,0.762,72.3769,15.387734,9.885519,12245.893660,2.232495e+11,6621.574336,...,"4,270,272",NaN,"3,919",35,"38,354,895","33,684,208",South America,NaN,NaN,116
70,ARM,Armenia,85,0.759,72.0431,13.116760,11.330300,13157.993900,1.386141e+10,4966.513471,...,"435,162",NaN,"4,250",NaN,"3,242,901","2,971,966",Asia,NaN,NaN,"1,430"
71,MEX,Mexico,86,0.758,70.2127,14.864440,9.221050,17896.294980,1.272839e+12,10045.680500,...,"6,788,390","+3,001","425,947",NaN,"19,810,846","131,562,772",North America,22.00,0.10,"3,238"
72,BRA,Brazil,87,0.754,72.7504,15.599060,8.128814,14369.888480,1.608981e+12,7507.160971,...,"36,249,161",NaN,"369,537",NaN,"63,776,166","215,353,593",South America,NaN,NaN,"1,716"
73,COL,Colombia,88,0.752,72.8296,14.442750,8.862860,14384.356660,3.144641e+11,6104.136709,...,"6,185,669",NaN,"33,965",342,"36,951,507","51,512,762",South America,NaN,NaN,659
74,VCT,Saint Vincent and the Grenadines,89,0.751,69.6291,14.672206,10.833430,11961.087920,9.041815e+08,8666.387041,...,"9,472",NaN,5,NaN,"113,886","111,551",North America,NaN,NaN,45
75,MDV,Maldives,90,0.747,79.9182,12.635610,7.322000,15448.127880,5.405576e+09,10366.293358,...,"163,687",NaN,"21,812",25,"2,213,831","540,985",Asia,NaN,NaN,"40,319"
76,DZA,Algeria,91,0.745,76.3767,14.626896,8.069284,10800.225460,1.630444e+11,3690.627878,...,"182,893",NaN,"81,825",NaN,"230,861","45,350,148",Africa,0.10,NaN,"1,804"
77,AZE,Azerbaijan,91,0.745,69.3658,13.496890,10.542970,14256.744560,5.462218e+10,5387.997975,...,"819,310",NaN,456,NaN,"7,562,699","10,300,205",Asia,NaN,NaN,44
78,TON,Tonga,91,0.745,70.9857,16.048571,11.392594,6822.031250,4.692313e+08,4426.000637,...,"15,638",NaN,"1,163",NaN,"535,009","107,749",Australia/Oceania,NaN,NaN,"10,794"
79,ECU,Ecuador,95,0.740,73.6700,14.624230,8.817120,10311.632730,1.061659e+11,5965.132871,...,"1,021,591",NaN,"1,401",759,"3,082,403","18,113,361",South America,NaN,NaN,77
80,MNG,Mongolia,96,0.739,70.9754,14.980350,9.423700,10588.225320,1.528644e+10,4566.140154,...,"1,005,728",NaN,4,192,"4,030,048","3,378,078",Asia,NaN,NaN,1
81,EGY,Egypt,97,0.731,70.2207,13.786500,9.573026,11731.690560,4.041428e+11,3698.834981,...,"442,182",NaN,"49,087",122,"3,693,367","106,156,692",Africa,NaN,NaN,462
82,TUN,Tunisia,97,0.731,73.7719,15.425382,7.431599,10257.544770,4.668674e+10,3807.139150,...,NaN,NaN,NaN,44,"5,006,704","12,046,656",Africa,NaN,NaN,"1,052"
83,FJI,Fiji,99,0.730,67.1140,14.736790,10.921548,9980.110866,4.296305e+09,4646.612723,...,"67,014",NaN,"1,017",NaN,"669,911","909,466",Australia/Oceania,NaN,NaN,"1,118"
84,SUR,Suriname,99,0.730,70.2743,13.035644,9.776801,12672.200330,2.984706e+09,4869.134226,...,NaN,NaN,NaN,NaN,"241,666","596,831",South America,NaN,NaN,"52,502"
85,UZB,Uzbekistan,101,0.727,70.8616,12.477140,11.895590,7916.785725,6.923890e+10,1983.064723,...,"241,486",NaN,"8,716",23,"1,377,915","34,382,084",Asia,NaN,NaN,254
86,JOR,Jordan,102,0.720,74.2563,10.646560,10.446680,9923.714974,4.574427e+10,4103.258966,...,"1,731,007",NaN,"1,868",59,"17,201,885","10,300,869",Asia,NaN,NaN,181
87,PRY,Paraguay,105,0.717,70.2617,12.987991,8.861840,12349.286000,3.949543e+10,5891.499965,...,NaN,NaN,NaN,7,"2,657,506","7,305,843",South America,NaN,NaN,"12,418"
88,PSE,"Palestine, State of",106,0.715,73.4727,13.358010,9.938480,6582.899416,1.803680e+10,3663.969055,...,"615,445",NaN,159,17,"3,078,533","5,345,541",Asia,NaN,NaN,30
89,LCA,Saint Lucia,106,0.715,71.1114,12.866110,8.545040,12048.303810,1.691275e+09,9414.226231,...,"29,095",NaN,524,NaN,"210,983","185,113",North America,NaN,NaN,"2,831"
90,GUY,Guyana,108,0.714,65.6734,12.502722,8.617477,22464.657340,8.044499e+09,9998.544311,...,"71,818",NaN,4,NaN,"726,398","794,045",South America,NaN,NaN,5
91,ZAF,South Africa,109,0.713,62.3410,13.643710,11.373160,12948.373250,4.190150e+11,7055.044776,...,"3,912,506",NaN,"59,713",192,"26,795,090","60,756,135",Africa,4.00,NaN,983
92,JAM,Jamaica,110,0.709,70.5003,13.404920,9.154629,8834.475670,1.465759e+10,5183.581305,...,"102,634",NaN,"48,439",NaN,"1,183,986","2,985,094",North America,NaN,NaN,"16,227"
93,WSM,Samoa,111,0.707,72.7675,12.418859,11.403800,5307.953374,8.438424e+08,3857.318464,...,"1,605",NaN,"15,101",NaN,"187,397","202,239",Australia/Oceania,NaN,NaN,"74,669"
94,LBN,Lebanon,112,0.706,75.0472,11.285870,8.718636,9525.831467,2.313194e+10,4136.146347,...,"1,087,587",NaN,"136,605",74,"4,795,578","6,684,849",Asia,10.00,0.10,"20,435"
95,IDN,Indonesia,114,0.705,67.5703,13.748894,8.556510,11466.068360,1.186093e+12,4332.709281,...,"6,581,989",+553,"5,945",NaN,"114,158,919","279,134,505",Asia,2.00,0.01,21
96,VNM,Viet Nam,115,0.703,73.6181,12.951932,8.370280,7867.371345,3.661376e+11,3756.489121,...,"10,615,014",+23,"869,254",7,"85,826,548","98,953,541",Asia,0.50,NaN,"8,784"
97,PHL,Philippines,116,0.699,69.2664,13.126570,8.969100,8920.428468,3.940864e+11,3460.530963,...,"4,007,064",+716,"9,120",162,"34,855,638","112,508,994",Asia,2.00,0.05,81
98,BWA,Botswana,117,0.693,61.1409,12.265138,10.340000,16198.318410,1.761479e+10,6805.221274,...,"326,969",NaN,42,1,"2,026,898","2,441,162",Africa,NaN,NaN,17
99,BOL,Bolivia (Plurinational State of),118,0.692,63.6304,14.946971,9.827750,8111.190194,4.040821e+10,3345.196589,...,"1,164,554",+136,"9,102",220,"2,705,422","11,992,656",South America,4.00,0.08,759
100,KGZ,Kyrgyzstan,118,0.692,69.9774,13.195300,11.374106,4566.303831,8.543424e+09,1276.700365,...,"196,406",NaN,"7,408",131,"1,907,195","6,728,271",Asia,NaN,NaN,"1,101"
101,IRQ,Iraq,121,0.686,70.3779,12.087473,7.905593,9977.249073,2.078893e+11,4775.377454,...,"2,439,497",NaN,673,21,"19,544,451","42,164,965",Asia,NaN,NaN,16
102,BLZ,Belize,123,0.683,70.4697,12.991690,8.847600,6309.099778,2.491500e+09,6228.267309,...,"70,085",NaN,9,6,"576,016","412,190",North America,NaN,NaN,22
103,MAR,Morocco,123,0.683,74.0419,14.151910,5.916000,7302.819170,1.428663e+11,3795.380127,...,"1,256,151",NaN,175,3,"13,001,033","37,772,756",Africa,NaN,NaN,5
104,SLV,El Salvador,125,0.675,70.7479,12.671348,7.150930,8295.665889,2.873694e+10,4551.184661,...,"179,410",NaN,"18,145",8,"2,610,114","6,550,389",North America,NaN,NaN,"2,770"
105,NIC,Nicaragua,126,0.667,73.8368,12.641358,7.144000,5624.793595,1.401302e+10,2045.535402,...,"4,225",NaN,"14,041",NaN,NaN,"6,779,100",North America,NaN,NaN,"2,071"
106,BTN,Bhutan,127,0.666,71.8150,13.225005,5.170262,9437.541512,2.539553e+09,3266.364905,...,"61,564",NaN,"1,063",NaN,"2,303,734","787,941",Asia,NaN,NaN,"1,349"
107,CPV,Cabo Verde,128,0.662,74.0518,12.554614,6.287719,6230.200199,1.936174e+09,3293.233054,...,"62,786",NaN,61,23,"401,622","567,678",Africa,NaN,NaN,107
108,BGD,Bangladesh,129,0.661,72.3811,12.441980,7.379060,5472.104781,4.162649e+11,2457.924880,...,"1,998,448",NaN,"10,120",NaN,"15,254,399","167,885,689",Asia,NaN,NaN,60
109,IND,India,132,0.633,67.2398,11.874620,6.655109,6589.980037,3.176295e+12,2256.590409,...,"44,179,712",NaN,"23,091",NaN,"922,033,777","1,406,631,776",Asia,NaN,NaN,16
110,GHA,Ghana,133,0.632,63.7954,12.047780,8.329887,5744.504017,7.759428e+10,2363.299296,...,"170,012",NaN,53,2,"2,534,561","32,395,450",Africa,NaN,NaN,2
111,GTM,Guatemala,135,0.627,69.2368,10.562450,5.681300,8723.285317,8.598575e+10,5025.542291,...,"1,224,161",NaN,"1,016",5,"7,119,398","18,584,039",North America,NaN,NaN,55
112,HND,Honduras,137,0.621,70.1229,10.132814,7.088480,5297.955301,2.848867e+10,2771.717461,...,NaN,NaN,NaN,105,"1,649,099","10,221,247",North America,NaN,NaN,"32,169"
113,NAM,Namibia,139,0.615,59.2690,11.927207,7.192013,8633.504452,1.231060e+10,4865.557765,...,"167,099",NaN,33,NaN,"1,062,663","2,633,874",Africa,NaN,NaN,13
114,LAO,Lao People's Democratic Republic,140,0.607,68.0608,10.136110,5.374000,7699.579617,1.882715e+10,2535.623432,...,NaN,NaN,NaN,NaN,"1,233,207","7,481,023",Asia,NaN,NaN,"28,020"

In [95]:
covid.to_excel('covidApril5th2023.xlsx', index = False)